import test from "node:test";
import assert from "node:assert/strict";
const base=process.env.E2E_BASE_URL ?? "http://localhost:4000";
const enabled=process.env.RUN_E2E==="true";
let cookie="";let attemptId="";
async function call(path:string,init:RequestInit={}){const r=await fetch(`${base}${path}`,{...init,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{}),...(init.headers??{})}});const set=r.headers.get("set-cookie");if(set)cookie=set.split(";")[0];return r;}
test("registration creates a student session",{skip:!enabled},async()=>{const r=await call("/api/auth/register",{method:"POST",body:JSON.stringify({name:"E2E Student",email:`e2e-${Date.now()}@example.test`,password:"SafeTestPass123"})});assert.equal(r.status,201);assert.ok(cookie);});
test("login and authenticated profile work",{skip:!enabled},async()=>{const me=await call("/api/auth/me");assert.equal(me.status,200);const update=await call("/api/profile",{method:"PUT",body:JSON.stringify({currentLevel:5,targetBand:6.5,examDate:"2030-06-01",dailyStudyMinutes:60})});assert.equal(update.status,200);});
test("practice submission saves and scores an attempt",{skip:!enabled},async()=>{const list=await call("/api/practice/reading/tests");const {tests}=await list.json() as any;assert.ok(tests.length);const testData=await call(`/api/practice/reading/tests/${tests[0].id}`);const {test:reading}=await testData.json() as any;const q=reading.passages[0].questions[0];const submit=await call(`/api/practice/reading/tests/${reading.id}/submit`,{method:"POST",body:JSON.stringify({answers:[{questionId:q.id,answer:"true"}]})});assert.equal(submit.status,201);});
test("writing submission and optional AI evaluation",{skip:!enabled},async()=>{const list=await call("/api/practice/writing/tasks");const {tasks}=await list.json() as any;assert.ok(tasks.length);const attempt=await call(`/api/practice/writing/tasks/${tasks[0].id}/attempts`,{method:"POST",body:JSON.stringify({responseText:"I agree because remote work can reduce commuting time and improve wellbeing for many workers."})});assert.equal(attempt.status,201);attemptId=(await attempt.json() as any).attempt.id;if(process.env.RUN_AI_E2E==="true"){const evaluate=await call(`/api/evaluations/writing/attempts/${attemptId}`,{method:"POST"});assert.equal(evaluate.status,201);}});
test("coach dashboard returns progress tracking",{skip:!enabled},async()=>{const plan=await call("/api/coach/plan/generate",{method:"POST",body:"{}"});assert.equal(plan.status,201);const dashboard=await call("/api/coach/dashboard");assert.equal(dashboard.status,200);const body=await dashboard.json() as any;assert.ok(Array.isArray(body.tasks));});
