"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "../../lib/api";
export default function Onboarding(){
  const router=useRouter();
  const [form,setForm]=useState({currentLevel:5,targetBand:6.5,examDate:"",dailyStudyMinutes:60,weakSkills:[] as string[]});
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{api<{profile:Partial<typeof form>}>("/api/profile").then(({profile})=>setForm(f=>({...f,currentLevel:Number(profile.currentLevel??5),targetBand:Number(profile.targetBand??6.5),dailyStudyMinutes:Number(profile.dailyStudyMinutes??60),examDate:profile.examDate?.slice(0,10)??"",weakSkills:profile.weakSkills??[]}))).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const toggle=(skill:string)=>setForm({...form,weakSkills:form.weakSkills.includes(skill)?form.weakSkills.filter(s=>s!==skill):[...form.weakSkills,skill]});
  return <main className="min-h-screen bg-mist p-5"><form className="card mx-auto mt-8 max-w-2xl" onSubmit={async e=>{e.preventDefault();if(loading||busy)return;setBusy(true);setError("");try{await api("/api/coach/onboarding",{method:"PUT",body:JSON.stringify({...form,currentLevel:Number(form.currentLevel),targetBand:Number(form.targetBand),dailyStudyMinutes:Number(form.dailyStudyMinutes)})});router.push("/dashboard/study-plan");}catch(e){setError(e instanceof Error?e.message:"Could not save your profile. Please try again.");}finally{setBusy(false);}}}>
    <a href="/" className="text-sm font-semibold text-ocean">← Overview</a><p className="mt-5 font-semibold tracking-widest text-ocean">YOUR LEARNING PROFILE</p><h1 className="mt-3 text-3xl font-bold">Let’s build your roadmap.</h1><p className="mt-2 text-slate-600">Set your goals. Saving opens your study plan and all dashboard menus.</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="label">Current IELTS level</span><input required type="number" step="0.5" min="0" max="9" value={form.currentLevel} onChange={e=>setForm({...form,currentLevel:Number(e.target.value)})}/></label><label><span className="label">Target band</span><input required type="number" step="0.5" min="0" max="9" value={form.targetBand} onChange={e=>setForm({...form,targetBand:Number(e.target.value)})}/></label><label><span className="label">Exam date</span><input required type="date" value={form.examDate} onChange={e=>setForm({...form,examDate:e.target.value})}/></label><label><span className="label">Daily study minutes</span><select value={form.dailyStudyMinutes} onChange={e=>setForm({...form,dailyStudyMinutes:Number(e.target.value)})}>{[30,45,60,90,120].map(minutes=><option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label></div>
    <fieldset className="mt-6"><legend className="label">Which skills feel hardest right now?</legend><div className="flex flex-wrap gap-2">{["listening","reading","writing","speaking"].map(skill=><button type="button" aria-pressed={form.weakSkills.includes(skill)} onClick={()=>toggle(skill)} className={form.weakSkills.includes(skill)?"btn-primary capitalize":"btn-secondary capitalize"} key={skill}>{skill}</button>)}</div></fieldset>
    {error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<button className="btn-primary mt-7" disabled={loading||busy}>{loading?"Loading your profile…":busy?"Saving your profile…":"Save and open my study plan →"}</button><p className="mt-4 text-sm text-slate-500">Today’s existing tasks and completed progress will be preserved. Updated preferences apply to your next daily plan.</p>
  </form></main>;
}
