import { additionalVideos, lessonTopic } from "./library-video-index.js";
import { creators } from "./library-creators.js";
import { englishLibrary } from "./library-english.js";
export type LibraryVideo = { id: string; title: string; channel: string; topic: string };
export type LibraryModule = { slug: string; title: string; description: string; icon: string; notes: string[]; notesBengali?:string[]; videos: LibraryVideo[] };
const video = (id: string, title: string, channel: string, topic: string): LibraryVideo => ({ id, title, channel, topic });
export const libraryModules: LibraryModule[] = [
  { slug: "00-introduction", title: "IELTS পরিচিতি", description: "শুরু থেকে — IELTS কী, কোন পরীক্ষা বেছে নেবেন, এবং প্রস্তুতি কীভাবে শুরু করবেন।", icon: "book", notes: ["আপনার বিশ্ববিদ্যালয়, ভিসা বা পেশাগত প্রতিষ্ঠানের শর্ত দেখে Academic অথবা General Training বেছে নিন। UKVI দরকার কি না, আবেদন গ্রহণকারী প্রতিষ্ঠানের কাছে নিশ্চিত করুন।", "Listening, Reading, Writing ও Speaking — চারটি দক্ষতা আলাদাভাবে অনুশীলন করুন। শুধু সামগ্রিক band নয়, প্রতিটি skill-এর প্রয়োজনীয় score লিখে রাখুন।", "প্রথমে একটি diagnostic practice দিন। ভুলের তালিকা করে প্রতিদিনের সময় ভাগ করুন: শেখা, practice, এবং ভুল বিশ্লেষণ।", "ফি, পরিচয়পত্র ও booking policy দেশ ও test centre অনুযায়ী বদলায়। নিবন্ধনের আগে British Council বা IDP-এর অফিসিয়াল নির্দেশনা দেখুন।"], videos: [video("j16s7ay3Bsw", "Overview of IELTS | IELTS Prepare by IDP (Episode 1)", "IELTS by IDP", "What is IELTS?"),video("Lcp8h9AT-Jg","IELTS Basics — Introduction to the IELTS Exam","engVid","What is IELTS?"),video("6IqMXqIEtMw","Introduction of IELTS | IELTS Class 01 | Free IELTS Course","IELTS Daily","What is IELTS?"),video("AOv0aKMhT40","IELTS test for UK visas (UKVI) — by IDP Education","IELTS by IDP","Choosing your test"),video("9CRnpLpTkUM","IELTS Academic or General Training: Which do you need?","E2 IELTS","Choosing your test")] },
  { slug: "01-listening", title: "Listening Module", description: "Question types, prediction, distractors ও answer checking — মন দিয়ে শুনে সঠিক উত্তর খুঁজুন।", icon: "headphones", notes: ["Audio শুরুর আগে প্রশ্ন পড়ে সম্ভাব্য answer type অনুমান করুন: নাম, সংখ্যা, স্থান নাকি noun।", "একই শব্দ শুনলেই উত্তর ধরে নেবেন না। Speaker আগের তথ্য সংশোধন করতে পারে — but, actually, instead-এর মতো সংকেত শুনুন।", "Word limit, spelling ও singular/plural পরীক্ষা করুন। অনুশীলনের পরে transcript দেখে ঠিক কোন শব্দটি বুঝতে পারেননি লিখুন।", "Paper ও computer পরীক্ষার answer-transfer নিয়ম এক নয়। নিজের নির্বাচিত পরীক্ষার বর্তমান official instructions অনুসরণ করুন।"], videos: [video("82YKeI784YU","Understand IELTS Listening in JUST 50 minutes!","E2 IELTS","Listening overview"),video("m7jjTTsbjec","The Ultimate Guide to IELTS Listening (2026)","E2 IELTS","Listening overview"),video("4waIW_RZg6o","IELTS Listening Test Format / Introduction for Academic and General Training","TakeIELTS / Cambridge IELTS","Listening overview"),video("tOFm-zoI6-w","Understand the IELTS test format: The ultimate guide","TakeIELTS","Listening overview"),video("mGxP5CJ1dD4","IELTS Listening: ALL Question Types! [+Examples!]","E2 IELTS","Question types")] },
  { slug: "02-reading", title: "Reading Module", description: "Skimming, scanning, paraphrase এবং True / False / Not Given নিয়ে ধাপে ধাপে প্রস্তুতি।", icon: "book", notes: ["Skimming দিয়ে passage-এর মূল বক্তব্য বুঝুন; scanning দিয়ে নাম, তারিখ বা নির্দিষ্ট তথ্য খুঁজুন।", "প্রশ্নের keyword-এর হুবহু শব্দ খোঁজার বদলে synonym ও paraphrase মিলিয়ে দেখুন।", "False মানে passage-এর সঙ্গে বিপরীত তথ্য। Not Given মানে সিদ্ধান্তের জন্য পর্যাপ্ত তথ্য নেই — নিজের সাধারণ জ্ঞান ব্যবহার করবেন না।", "প্রতি উত্তরের evidence passage-এ চিহ্নিত করুন। সময় ধরে practice করুন এবং ভুল প্রশ্নের ধরন আলাদা করে রাখুন।"], videos: [video("JRiHEUyd0Qg","IELTS Reading Test Format / Introduction for Academic and General Training","TakeIELTS / Cambridge IELTS","Reading overview"),video("IUcJREhUKGg","IELTS Reading | SUPER METHODS #1 with Jay!","E2 IELTS","Reading strategies"),video("KadZ3KYzM0I","15 Reading Tips for IELTS Academic & IELTS General","E2 IELTS","Reading strategies"),video("U-GL5-VjeZM","Understand the IELTS test format","TakeIELTS","Reading overview"),video("hoOVjmKf_xw","IELTS Reading True, False, Not Given with Alex & Jay","E2 IELTS","Question types")] },
  { slug: "03-writing", title: "Writing Module", description: "Task 1 ও Task 2 — structure, clear ideas, vocabulary এবং grammar-এর ব্যবহার।", icon: "pen", notes: ["Task 2-তে লেখার আগে প্রশ্নের সব অংশ চিহ্নিত করুন। নিজের অবস্থান ও প্রতিটি body paragraph-এর মূল যুক্তি পরিকল্পনা করুন।", "একটি paragraph-এ একটি main idea, ব্যাখ্যা ও প্রাসঙ্গিক উদাহরণ রাখুন। মুখস্থ template দিয়ে প্রশ্ন এড়িয়ে যাবেন না।", "Academic Task 1-এ প্রধান trend বা পার্থক্য নিয়ে overview লিখুন। তথ্যের বাইরে কারণ বা অনুমান যোগ করবেন না।", "Grammar ও vocabulary জটিল হলেই ভালো নয় — সঠিক ও স্বাভাবিক ব্যবহার জরুরি। শেষে spelling, agreement এবং punctuation পরীক্ষা করুন।"], videos: [video("_V4IpM05k5Q","IELTS Writing Task 2 Masterclass: Top Marks for Each Criteria","E2 IELTS","Writing assessment"),video("JV7cN-RrcJI","IELTS Writing Task 2 Marking Criteria: Task Response","IELTS preparation","Task response"),video("w_HVUbayNF0","IELTS Writing Guide | Band Descriptors Explained","IELTS preparation","Writing assessment"),video("iurqANTFj2M","How IELTS Writing Is Scored: Cohesion & Coherence","IELTS preparation","Coherence and cohesion"),video("XATlmM286wg","IELTS Writing task 1: line graph","IELTS preparation","Academic Task 1")] },
  { slug: "04-speaking", title: "Speaking Module", description: "Part 1, cue card ও discussion — স্বাভাবিক, পরিষ্কার এবং বিস্তৃত উত্তর দিতে শিখুন।", icon: "mic", notes: ["Part 1-এ সরাসরি উত্তর দিয়ে কারণ বা ছোট উদাহরণ যোগ করুন। মুখস্থ বক্তব্যের বদলে স্বাভাবিকভাবে কথা বলুন।", "Cue card-এর প্রস্তুতিতে keyword লিখুন, সম্পূর্ণ বাক্য নয়। Past, present ও future নিয়ে কথা বাড়ানোর চেষ্টা করুন।", "Part 3-এ নিজের মতামত, কারণ ও উদাহরণ দিন। প্রয়োজনে অন্য দৃষ্টিভঙ্গির সঙ্গে তুলনা করুন।", "নিজের recording শুনে pause, repeated words ও অস্পষ্ট pronunciation চিহ্নিত করুন। Accent নকল করার চেয়ে বোঝা যায় এমন speech বেশি গুরুত্বপূর্ণ।"], videos: [video("QGUNvn9WX3g","How IELTS Speaking Is Scored | Band Descriptors Explained in Simple Words!","IELTS preparation","Speaking assessment"),video("wqROk4RljLM","IELTS Speaking: Band Descriptors Explained","IELTS preparation","Speaking assessment"),video("CpaBmXtILAw","Understanding the IELTS Speaking Band Descriptors: What Examiners Want?","IELTS preparation","Speaking assessment"),video("KB7y9TM21ew","IELTS Speaking Test Band Descriptors","IELTS preparation","Speaking assessment"),video("FjgeI68Iry8","IELTS Speaking Part 1: Answer Any Question Confidently (Band 7+)","IELTS preparation","Speaking Part 1")] },
  { slug: "05-grammar", title: "Grammar Foundations", description: "Tenses, conditionals, sentence structure — IELTS-এর জন্য essential grammar।", icon: "pen", notes: ["Past simple নির্দিষ্ট অতীত সময়ে শেষ হওয়া কাজ বোঝায়। Present perfect বর্তমানের সঙ্গে সম্পর্কিত অভিজ্ঞতা বা ফল বোঝায়।", "প্রতি sentence-এ subject ও verb আছে কি না দেখুন। দীর্ঘ বাক্যে agreement-এর ভুল বেশি হয়।", "Conditionals দিয়ে বাস্তব সম্ভাবনা ও কাল্পনিক পরিস্থিতির পার্থক্য প্রকাশ করুন; অকারণে জটিল structure চাপিয়ে দেবেন না।", "নিজের writing থেকে পাঁচটি grammar error সংগ্রহ করুন। Correct version লিখে একই structure দিয়ে নতুন বাক্য তৈরি করুন।"], videos: [video("0PJh5M68AzI","Learn English Tenses: PAST SIMPLE & PRESENT PERFECT","engVid","Tenses"),video("VZH0le_xkHw","Learn English Tenses: FUTURE with GOING TO & Present Continuous","engVid","Tenses"),video("WHf2Q2vtgPM","Past Simple, Past Continuous, Past Perfect, or Present Perfect?","engVid","Tenses"),video("CEa8IZy7hLk","Practice the PRESENT PERFECT TENSE in English!","engVid","Tenses"),video("44FRkmuDLSw","Master English Conditionals: Zero, First, Second, Third & Mixed","English grammar","Conditionals")] },
  { slug: "06-vocabulary", title: "Vocabulary Building", description: "Word lists নয়, context ও collocation দিয়ে নিজের Lexical Resource বাড়ান।", icon: "book", notes: ["নতুন শব্দের meaning-এর পাশাপাশি pronunciation, word family ও একটি natural collocation লিখুন।", "একই শব্দ ব্যবহার করে নিজের জীবনের সঙ্গে সম্পর্কিত বাক্য বানান। শুধু বাংলা অর্থ মুখস্থ করলে productive vocabulary তৈরি হয় না।", "Environment, education, technology-এর মতো topic অনুযায়ী vocabulary সাজান। Synonym সব context-এ বিনিময়যোগ্য নয়।", "Spaced review করুন: আজ, কয়েক দিন পরে, আবার পরের সপ্তাহে। শব্দ চিনতে পারা আর speaking-এ ব্যবহার করতে পারা আলাদা দক্ষতা।"], videos: [video("BoVklnowqSQ","IELTS VOCABULARY: Academic Word List (AWL)","IELTS preparation","Academic vocabulary"),video("c5UrjfguQV4","How to use the Academic Word List for IELTS preparation","IELTS preparation","Academic vocabulary"),video("_YrlbN87Wp8","IELTS & TOEFL Academic Vocabulary — Verbs (AWL)","engVid","Word families"),video("RiUTWwdhMDg","IELTS & TOEFL Academic Vocabulary — Nouns (AWL)","engVid","Word families"),video("fuXxanTQZsw","IELTS Vocabulary and Ideas: Environment | Writing & Speaking","IELTS preparation","Topic vocabulary")] },
  { slug: "07-pronunciation", title: "Pronunciation Training", description: "Sounds, word stress ও connected speech — পরিষ্কারভাবে কথা বলার অনুশীলন।", icon: "mic", notes: ["Dictionary audio শুনে word stress চিহ্নিত করুন। শুধু spelling দেখে উচ্চারণ অনুমান করবেন না।", "V এবং W-এর মতো confusing sound আলাদা করে practice করুন; নিজের recording-এর সঙ্গে original audio তুলনা করুন।", "Short sentence শুনে shadowing করুন। শব্দের পাশাপাশি rhythm, pause ও intonation অনুসরণ করুন।", "Pronunciation-এর লক্ষ্য intelligibility: শ্রোতা যেন সহজে বুঝতে পারেন। নির্দিষ্ট দেশের accent দরকার নেই।"], videos: [video("SOm7y1pwROg","Learn the IPA: International Phonetic Alphabet","English pronunciation","Sounds and IPA"),video("mWMdTwQSvWo","International Phonetic Alphabet | Learn English Pronunciation","English pronunciation","Sounds and IPA"),video("htmkbIboG9Q","RP Phonemes: Pronunciation Tips","BBC Learning English","Sounds and IPA"),video("r6o6NOjGv7I","Accent Training Exercises: Learn Vowel Sounds with the IPA","English pronunciation","Vowel sounds"),video("d4qL0zrCauo","How to Pronounce the V and W","English pronunciation","Confusing sounds")] },
  { slug: "08-test-strategy", title: "Test-Taking Strategy", description: "Study plan থেকে test day — সময় ব্যবস্থাপনা, mock tests এবং focused review।", icon: "target", notes: ["আপনার available time ও weakest skill দেখে weekly plan করুন। প্রতিটি practice-এর পরে review time রাখুন।", "Untimed practice দিয়ে technique শিখুন, তারপর timed practice দিয়ে pacing পরীক্ষা করুন।", "Mock test-এর ফল দেখে শুধু score নয়, ভুলের কারণ লিখুন: vocabulary, concentration, technique নাকি time pressure।", "Test day-এর আগে venue, arrival time, ID ও permitted items official centre instructions থেকে নিশ্চিত করুন।"], videos: [video("LnkA5W-xyFM","How to Study for IELTS in 4 to 8 Weeks","IELTS preparation","Study planning"),video("5W5CcOe-DD8","How to Study for IELTS in 8 Weeks or More","IELTS preparation","Study planning"),video("iHtUwpxBRcg","How to Prepare for IELTS | Study Plans for 7 Days / 1 Month / 3 Months","IELTS preparation","Study planning"),video("EVkazzbxvVU","How to Prepare for IELTS in 30 Days","IELTS preparation","Study planning"),video("NXJa7GFjY3U","IELTS Full Mock Test (with Jay & Mark)","E2 IELTS","Mock practice")] },
  { slug: "09-after-the-test", title: "Test-এর পরে যা যা", description: "Results, Test Report Form, EOR ও retake — পরবর্তী পদক্ষেপ বুঝুন।", icon: "chart", notes: ["Result প্রকাশ হলে প্রত্যেক skill score-এর সঙ্গে আপনার প্রতিষ্ঠানের শর্ত মিলিয়ে দেখুন। শুধু overall score যথেষ্ট নাও হতে পারে।", "Test Report Form ও result delivery সম্পর্কে নিজের test provider-এর নির্দেশনা পড়ুন। ব্যক্তিগত তথ্য বা result public group-এ শেয়ার করবেন না।", "Enquiry on Results-এর fee, deadline ও refund policy পরিবর্তিত হতে পারে। সিদ্ধান্তের আগে provider-এর বর্তমান নিয়ম যাচাই করুন।", "Retake বা One Skill Retake আপনার test ও institution-এর জন্য গ্রহণযোগ্য কি না নিশ্চিত করুন। নিচের পুরোনো video-তে বলা policy বর্তমান নাও হতে পারে।"], videos: [video("If49Wt0hSzA","How to check your IELTS results online","TakeIELTS Preparation","Understanding results"),video("9IpaMYNdZVQ","What Is The IELTS Test Report Form (TRF)?","IELTS preparation","Understanding results"),video("_C6qUGSOT88","How to check your IELTS results online in five minutes","IELTS preparation","Understanding results"),video("zO-ujHYMYfM","Enquiry on Results — Is it worth requesting a remark?","IELTS preparation","EOR and retakes"),video("n7aJ0AJBjqA","The Power of Re-Evaluation: IELTS Results with EOR","Asad Yaqub","EOR and retakes")] },
  { slug: "10-mock-tests", title: "Mock Tests ও Practice Library", description: "Video practice, timed tests এবং error review — শেখা technique কাজে লাগান।", icon: "layers", notes: ["প্রথমে instructions পড়ে test conditions-এ উত্তর দিন। উত্তর আগে দেখে ফেললে practice score diagnostic থাকে না।", "একটি ছোট sample থেকে official IELTS band নির্ধারণ করবেন না। Official complete practice material-এর score guidance ব্যবহার করুন।", "Answer checking-এর পরে ভুলের evidence ও সঠিক reasoning লিখুন। কয়েক দিন পরে একই question type আবার practice করুন।", "YouTube video creators-এর নিজস্ব উপকরণ। Official sample tests-এর জন্য IELTS, British Council বা IDP-এর website ব্যবহার করুন।"], videos: [video("Nt8PTy68SQI","IELTS Listening Practice Test | Cambridge 19 Test 1 with Answers","IELTS practice","Listening practice"),video("WdffnpY8wAo","Cambridge IELTS 18 | Listening Test with Answers","IELTS practice","Listening practice"),video("Y3hF8UXOkxs","Listening Mock Test | Asad Yaqub’s IELTS Masterclass","Asad Yaqub","Listening practice"),video("9Yqdi9maomw","Cambridge IELTS Book 19 — Listening Test 1 (REVOICED)","IELTS practice","Listening practice"),video("k_ucGw9cXDI","Full IELTS Mock Test: Practice & Answers for Every Section","IELTS practice","Full mock practice")] },
];

export function youtubeId(value: string): string | null {
  try { const url = new URL(value); if (url.protocol !== "https:") return null; const host = url.hostname.toLowerCase(); let id: string | null = null;
    if (host === "youtu.be") id = url.pathname.slice(1).split("/")[0];
    else if (["youtube.com", "www.youtube.com", "m.youtube.com", "youtube-nocookie.com", "www.youtube-nocookie.com"].includes(host)) id = url.pathname === "/watch" ? url.searchParams.get("v") : /^\/(embed|shorts)\//.test(url.pathname) ? url.pathname.split("/")[2] : null;
    return id && /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
  } catch { return null; }
}
for (const module of libraryModules) {
  const english=englishLibrary[module.slug];
  if(english){module.notesBengali=module.notes;module.title=english.title;module.description=english.description;module.notes=english.notes;}
  for (const line of (additionalVideos[module.slug]??"").split("\n").filter(Boolean)) {
    const id=line.slice(0,11),title=line.slice(12);
    if(!module.videos.some(v=>v.id===id))module.videos.push(video(id,title,"See creator on YouTube",lessonTopic(module.slug,title)));
  }
  for(const lesson of module.videos)lesson.channel=creators.get(lesson.id)??"See creator on YouTube";
}
