import { Router } from "express";
import multer from "multer";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import type {PoolClient} from "pg";
import { pool } from "../db/pool.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
import type { AuthenticatedRequest } from "../types.js";

const router = Router();
const contentRoles = ["admin", "content_manager"] as const;
const option = z.object({ label: z.string(), value: z.string() });
const question = z.object({ questionNumber: z.number().int().positive(), questionType: z.string(), prompt: z.string().min(1), options: z.array(option).default([]), acceptedAnswers: z.array(z.string()).min(1), explanation: z.string().nullable().optional(), points: z.number().int().positive().default(1) });
const answerPayload = z.object({ answers: z.array(z.object({ questionId: z.string().uuid(), answer: z.string().max(1000) })) });
const test = z.object({ title: z.string().min(3).max(200), description: z.string().nullable().optional(), durationMinutes: z.number().int().min(1).max(180).default(30), isPublished: z.boolean().default(false) });
const uploadDir = join(process.cwd(), "uploads"); mkdirSync(uploadDir, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: (_r, _f, cb) => cb(null, uploadDir), filename: (_r, file, cb) => cb(null, `${randomUUID()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_")}`) }), limits: { fileSize: 30 * 1024 * 1024 }, fileFilter: (_r, f, cb) => cb(null, f.mimetype.startsWith("audio/")) });
const isStaff = (req: AuthenticatedRequest) => req.user?.role === "admin" || req.user?.role === "content_manager";
const normalize = (s: string) => s.trim().toLowerCase().replace(/\s+/g, " ");

router.get("/listening/tests", requireAuth, async (req: AuthenticatedRequest, res, next) => { try { const visibility = isStaff(req) ? "" : "WHERE is_published = TRUE"; const result = await pool.query(`SELECT id,title,description,duration_minutes AS \"durationMinutes\",is_published AS \"isPublished\" FROM listening_tests ${visibility} ORDER BY created_at DESC`); res.json({ tests: result.rows }); } catch(e){next(e)} });
router.post("/listening/tests", requireAuth, requireRole(...contentRoles), async (req: AuthenticatedRequest,res,next) => { try { const d=test.parse(req.body); const r=await pool.query("INSERT INTO listening_tests(title,description,duration_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id,title",[d.title,d.description??null,d.durationMinutes,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]}); } catch(e){ if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)} });
router.post("/listening/sections/:sectionId/audio", requireAuth, requireRole(...contentRoles), upload.single("audio"), async (req,res,next) => { try { if(!req.file)return res.status(400).json({message:"An audio file is required"}); const r=await pool.query("UPDATE listening_sections SET audio_url=$1 WHERE id=$2 RETURNING id,audio_url AS \"audioUrl\"",[`/uploads/${req.file.filename}`,req.params.sectionId]); if(!r.rowCount)return res.status(404).json({message:"Section not found"});res.json({section:r.rows[0]}); }catch(e){next(e)} });
router.post("/listening/tests/:testId/sections", requireAuth, requireRole(...contentRoles), async (req,res,next)=>{try{const d=z.object({sectionNumber:z.number().int().min(1).max(4),title:z.string().optional(),instructions:z.string().optional()}).parse(req.body);const r=await pool.query("INSERT INTO listening_sections(test_id,section_number,title,instructions) VALUES($1,$2,$3,$4) RETURNING id,section_number AS \"sectionNumber\"",[req.params.testId,d.sectionNumber,d.title??null,d.instructions??null]);res.status(201).json({section:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/listening/sections/:sectionId/questions", requireAuth, requireRole(...contentRoles), async(req,res,next)=>{try{const q=question.parse(req.body);const r=await pool.query("INSERT INTO listening_questions(section_id,question_number,question_type,prompt,options,accepted_answers,explanation,points) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[req.params.sectionId,q.questionNumber,q.questionType,q.prompt,JSON.stringify(q.options),JSON.stringify(q.acceptedAnswers),q.explanation??null,q.points]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/listening/tests/:testId", requireAuth, async(req:AuthenticatedRequest,res,next)=>{try{const published=isStaff(req)?"":"AND t.is_published=TRUE";const r=await pool.query(`SELECT t.id,t.title,t.description,t.duration_minutes AS "durationMinutes",COALESCE(json_agg(json_build_object('id',s.id,'sectionNumber',s.section_number,'title',s.title,'audioUrl',s.audio_url,'transcript',s.transcript,'instructions',s.instructions,'questions',(SELECT COALESCE(json_agg(json_build_object('id',q.id,'questionNumber',q.question_number,'questionType',q.question_type,'prompt',q.prompt,'options',q.options,'points',q.points) ORDER BY q.question_number),'[]') FROM listening_questions q WHERE q.section_id=s.id)) ORDER BY s.section_number) FILTER(WHERE s.id IS NOT NULL),'[]') AS sections FROM listening_tests t LEFT JOIN listening_sections s ON s.test_id=t.id WHERE t.id=$1 ${published} GROUP BY t.id`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});

async function submitObjective(kind:"listening"|"reading",req:AuthenticatedRequest,res:any,next:any){
  let client:PoolClient|undefined;
  try{
    client=await pool.connect();
    const d=answerPayload.extend({submissionId:z.string().uuid().optional(),elapsedSeconds:z.number().int().min(0).max(86400).optional()}).parse(req.body);
    const groupTable=kind==="listening"?"listening_sections":"reading_passages",groupColumn=kind==="listening"?"section_id":"passage_id";
    const available=await client.query(`SELECT q.id,q.question_number AS "questionNumber",q.prompt,q.accepted_answers AS "acceptedAnswers",q.explanation,q.points FROM ${kind}_questions q JOIN ${groupTable} s ON q.${groupColumn}=s.id JOIN ${kind}_tests t ON s.test_id=t.id WHERE t.id=$1 AND t.is_published=TRUE ORDER BY q.question_number`,[req.params.testId]);
    if(!available.rowCount)return res.status(404).json({message:"Published test not found"});
    await client.query("BEGIN");
    const id=d.submissionId??randomUUID(),total=available.rows.reduce((n,q)=>n+q.points,0);
    const inserted=await client.query(`INSERT INTO ${kind}_attempts(id,user_id,test_id,status,started_at,submitted_at,raw_score,total_points) VALUES($1,$2,$3,'submitted',NOW()-($4::int*INTERVAL '1 second'),NOW(),0,$5) ON CONFLICT(id) DO NOTHING RETURNING id`,[id,req.user!.id,req.params.testId,d.elapsedSeconds??0,total]);
    const attempt=await client.query(`SELECT id,raw_score AS "rawScore",total_points AS "totalPoints",submitted_at AS "submittedAt" FROM ${kind}_attempts WHERE id=$1 AND user_id=$2 AND test_id=$3 FOR UPDATE`,[id,req.user!.id,req.params.testId]);
    if(!attempt.rowCount){await client.query("ROLLBACK");return res.status(409).json({message:"Start a new attempt before submitting."});}
    if(inserted.rowCount){
      const byId=new Map(available.rows.map(q=>[q.id,q])),seen=new Set<string>();let score=0;
      for(const input of d.answers){if(!byId.has(input.questionId)||seen.has(input.questionId))continue;seen.add(input.questionId);const q=byId.get(input.questionId)!;const correct=q.acceptedAnswers.some((a:string)=>normalize(a)===normalize(input.answer));if(correct)score+=q.points;await client.query(`INSERT INTO ${kind}_answers(attempt_id,question_id,answer,is_correct) VALUES($1,$2,$3,$4)`,[id,input.questionId,JSON.stringify(input.answer),correct]);}
      await client.query(`UPDATE ${kind}_attempts SET raw_score=$1 WHERE id=$2`,[score,id]);attempt.rows[0].rawScore=score;
    }
    const saved=await client.query(`SELECT question_id AS "questionId",answer,is_correct AS correct FROM ${kind}_answers WHERE attempt_id=$1`,[id]);
    const savedById=new Map(saved.rows.map(a=>[a.questionId,a]));
    const feedback=available.rows.map(q=>({...q,answer:savedById.get(q.id)?.answer??"",correct:savedById.get(q.id)?.correct??false}));
    await client.query("COMMIT");res.status(inserted.rowCount?201:200).json({attempt:attempt.rows[0],feedback});
  }catch(e){if(client)await client.query("ROLLBACK");if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e);}finally{client?.release();}
}
for(const kind of ["reading","listening"] as const){
  router.get("/"+kind+"/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const r=await pool.query(`SELECT a.id,a.test_id AS "testId",t.title,a.raw_score AS "rawScore",a.total_points AS "totalPoints",a.submitted_at AS "submittedAt" FROM ${kind}_attempts a JOIN ${kind}_tests t ON t.id=a.test_id WHERE a.user_id=$1 AND a.status='submitted' ORDER BY a.submitted_at DESC LIMIT 30`,[req.user!.id]);res.json({attempts:r.rows});}catch(e){next(e);}});
  router.get("/"+kind+"/attempts/:id",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{
    const id=z.string().uuid().parse(req.params.id),groupTable=kind==="reading"?"reading_passages":"listening_sections",groupColumn=kind==="reading"?"passage_id":"section_id";
    const attempt=await pool.query(`SELECT a.id,a.test_id AS "testId",t.title,a.raw_score AS "rawScore",a.total_points AS "totalPoints",a.submitted_at AS "submittedAt" FROM ${kind}_attempts a JOIN ${kind}_tests t ON t.id=a.test_id WHERE a.id=$1 AND a.user_id=$2 AND a.status='submitted'`,[id,req.user!.id]);if(!attempt.rowCount)return res.status(404).json({message:"Attempt not found"});
    const feedback=await pool.query(`SELECT q.id,q.question_number AS "questionNumber",q.prompt,q.accepted_answers AS "acceptedAnswers",q.explanation,q.points,COALESCE(a.answer,'""'::jsonb) AS answer,COALESCE(a.is_correct,FALSE) AS correct FROM ${kind}_questions q JOIN ${groupTable} g ON g.id=q.${groupColumn} LEFT JOIN ${kind}_answers a ON a.question_id=q.id AND a.attempt_id=$1 WHERE g.test_id=$2 ORDER BY q.question_number`,[id,attempt.rows[0].testId]);res.json({attempt:attempt.rows[0],feedback:feedback.rows});
  }catch(e){next(e);}});
}
router.post("/listening/tests/:testId/submit",requireAuth,(req,res,next)=>submitObjective("listening",req,res,next));

router.get("/reading/tests",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,description,duration_minutes AS "durationMinutes" FROM reading_tests ${where} ORDER BY created_at DESC`);res.json({tests:r.rows})}catch(e){next(e)}});
router.post("/reading/tests",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=test.parse(req.body);const r=await pool.query("INSERT INTO reading_tests(title,description,duration_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id,title",[d.title,d.description??null,d.durationMinutes,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/reading/tests/:testId/passages",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const d=z.object({passageNumber:z.number().int().min(1).max(3),title:z.string().min(1),body:z.string().min(1)}).parse(req.body);const r=await pool.query("INSERT INTO reading_passages(test_id,passage_number,title,body) VALUES($1,$2,$3,$4) RETURNING id",[req.params.testId,d.passageNumber,d.title,d.body]);res.status(201).json({passage:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/reading/passages/:passageId/questions",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const q=question.parse(req.body);const r=await pool.query("INSERT INTO reading_questions(passage_id,question_number,question_type,prompt,options,accepted_answers,explanation,points) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[req.params.passageId,q.questionNumber,q.questionType,q.prompt,JSON.stringify(q.options),JSON.stringify(q.acceptedAnswers),q.explanation??null,q.points]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/reading/tests/:testId",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const publication=isStaff(req)?"":"AND t.is_published=TRUE";const r=await pool.query(`SELECT t.id,t.title,t.description,t.duration_minutes AS "durationMinutes",COALESCE(json_agg(json_build_object('id',p.id,'passageNumber',p.passage_number,'title',p.title,'body',p.body,'questions',(SELECT COALESCE(json_agg(json_build_object('id',q.id,'questionNumber',q.question_number,'questionType',q.question_type,'prompt',q.prompt,'options',q.options,'points',q.points) ORDER BY q.question_number),'[]') FROM reading_questions q WHERE q.passage_id=p.id)) ORDER BY p.passage_number) FILTER(WHERE p.id IS NOT NULL),'[]') AS passages FROM reading_tests t LEFT JOIN reading_passages p ON p.test_id=t.id WHERE t.id=$1 ${publication} GROUP BY t.id`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});
router.post("/reading/tests/:testId/submit",requireAuth,(req,res,next)=>submitObjective("reading",req,res,next));

router.get("/writing/tasks",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,task_type AS "taskType",category,prompt,visual_url AS "visualUrl",time_limit_minutes AS "timeLimitMinutes" FROM writing_tasks ${where} ORDER BY created_at DESC`);res.json({tasks:r.rows})}catch(e){next(e)}});
router.post("/writing/tasks",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({title:z.string().min(3),taskType:z.enum(["task_1","task_2"]),category:z.string().min(2),prompt:z.string().min(10),visualUrl:z.string().url().nullable().optional(),timeLimitMinutes:z.number().int().min(5).max(90).default(40),isPublished:z.boolean().default(false)}).parse(req.body);const r=await pool.query("INSERT INTO writing_tasks(title,task_type,category,prompt,visual_url,time_limit_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[d.title,d.taskType,d.category,d.prompt,d.visualUrl??null,d.timeLimitMinutes,d.isPublished,req.user!.id]);res.status(201).json({task:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/writing/tasks/:taskId/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({responseText:z.string().min(1).max(20000)}).parse(req.body);const visible=await pool.query("SELECT 1 FROM writing_tasks WHERE id=$1 AND is_published=TRUE",[req.params.taskId]);if(!visible.rowCount)return res.status(404).json({message:"Task not found"});const count=d.responseText.trim().split(/\s+/).filter(Boolean).length;const r=await pool.query("INSERT INTO writing_attempts(user_id,task_id,response_text,word_count) VALUES($1,$2,$3,$4) RETURNING id,word_count AS \"wordCount\",submitted_at AS \"submittedAt\"",[req.user!.id,req.params.taskId,d.responseText,count]);res.status(201).json({attempt:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/writing/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const r=await pool.query("SELECT a.id,a.word_count AS \"wordCount\",a.submitted_at AS \"submittedAt\",t.title,t.task_type AS \"taskType\" FROM writing_attempts a JOIN writing_tasks t ON t.id=a.task_id WHERE a.user_id=$1 ORDER BY a.submitted_at DESC",[req.user!.id]);res.json({attempts:r.rows})}catch(e){next(e)}});

router.get("/speaking/tests",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,instructions FROM speaking_tests ${where} ORDER BY created_at DESC`);res.json({tests:r.rows})}catch(e){next(e)}});
router.post("/speaking/tests",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({title:z.string().min(3),instructions:z.string().nullable().optional(),isPublished:z.boolean().default(false)}).parse(req.body);const r=await pool.query("INSERT INTO speaking_tests(title,instructions,is_published,created_by) VALUES($1,$2,$3,$4) RETURNING id,title",[d.title,d.instructions??null,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/speaking/tests/:testId/questions",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const d=z.object({part:z.enum(["part_1","part_2","part_3"]),questionNumber:z.number().int().positive(),prompt:z.string().min(1),cuePoints:z.array(z.string()).default([]),preparationSeconds:z.number().int().min(0).max(300).default(0),responseSeconds:z.number().int().min(15).max(600).default(60)}).parse(req.body);const r=await pool.query("INSERT INTO speaking_questions(test_id,part,question_number,prompt,cue_points,preparation_seconds,response_seconds) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id",[req.params.testId,d.part,d.questionNumber,d.prompt,JSON.stringify(d.cuePoints),d.preparationSeconds,d.responseSeconds]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/speaking/tests/:testId",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const publication=isStaff(req)?"":"AND is_published=TRUE";const r=await pool.query(`SELECT id,title,instructions,(SELECT COALESCE(json_agg(json_build_object('id',q.id,'part',q.part,'questionNumber',q.question_number,'prompt',q.prompt,'cuePoints',q.cue_points,'preparationSeconds',q.preparation_seconds,'responseSeconds',q.response_seconds) ORDER BY q.part,q.question_number),'[]') FROM speaking_questions q WHERE q.test_id=speaking_tests.id) AS questions FROM speaking_tests WHERE id=$1 ${publication}`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});
router.post("/speaking/tests/:testId/attempts",requireAuth,upload.single("audio"),async(req:AuthenticatedRequest,res,next)=>{try{const questionId=z.string().uuid().parse(req.body.questionId);const test=await pool.query("SELECT 1 FROM speaking_tests WHERE id=$1 AND is_published=TRUE",[req.params.testId]);if(!test.rowCount)return res.status(404).json({message:"Test not found"});const audioUrl=req.file?`/uploads/${req.file.filename}`:null;const r=await pool.query("INSERT INTO speaking_attempts(user_id,test_id,question_id,audio_url,duration_seconds) VALUES($1,$2,$3,$4,$5) RETURNING id,audio_url AS \"audioUrl\",submitted_at AS \"submittedAt\"",[req.user!.id,req.params.testId,questionId,audioUrl,Number(req.body.durationSeconds)||null]);res.status(201).json({attempt:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:"A valid question is required"});next(e)}});
router.get("/speaking/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const r=await pool.query("SELECT a.id,a.audio_url AS \"audioUrl\",a.submitted_at AS \"submittedAt\",q.part,q.prompt FROM speaking_attempts a LEFT JOIN speaking_questions q ON q.id=a.question_id WHERE a.user_id=$1 ORDER BY a.submitted_at DESC",[req.user!.id]);res.json({attempts:r.rows})}catch(e){next(e)}});
export default router;
