import { Router } from "express";
import multer from "multer";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { pool } from "../db/pool.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
import type { AuthenticatedRequest } from "../types.js";

const router = Router();
const contentRoles = ["admin", "content_manager"] as const;
const option = z.object({ label: z.string(), value: z.string() });
const question = z.object({ questionNumber: z.number().int().positive(), questionType: z.string(), prompt: z.string().min(1), options: z.array(option).default([]), acceptedAnswers: z.array(z.string()).min(1), explanation: z.string().nullable().optional(), points: z.number().int().positive().default(1) });
const answerPayload = z.object({ answers: z.array(z.object({ questionId: z.string().uuid(), answer: z.string().max(1000) })) });
const test = z.object({ title: z.string().min(3).max(200), description: z.string().nullable().optional(), durationMinutes: z.number().int().min(1).max(180).default(30), isPublished: z.boolean().default(false) });
const uploadDir = join(process.cwd(), "uploads"); mkdirSync(uploadDir, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: (_r, _f, cb) => cb(null, uploadDir), filename: (_r, file, cb) => cb(null, `${randomUUID()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_")}`) }), limits: { fileSize: 30 * 1024 * 1024 }, fileFilter: (_r, f, cb) => cb(null, f.mimetype.startsWith("audio/")) });
const isStaff = (req: AuthenticatedRequest) => req.user?.role === "admin" || req.user?.role === "content_manager";
const normalize = (s: string) => s.trim().toLowerCase().replace(/\s+/g, " ");

router.get("/listening/tests", requireAuth, async (req: AuthenticatedRequest, res, next) => { try { const visibility = isStaff(req) ? "" : "WHERE is_published = TRUE"; const result = await pool.query(`SELECT id,title,description,duration_minutes AS \"durationMinutes\",is_published AS \"isPublished\" FROM listening_tests ${visibility} ORDER BY created_at DESC`); res.json({ tests: result.rows }); } catch(e){next(e)} });
router.post("/listening/tests", requireAuth, requireRole(...contentRoles), async (req: AuthenticatedRequest,res,next) => { try { const d=test.parse(req.body); const r=await pool.query("INSERT INTO listening_tests(title,description,duration_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id,title",[d.title,d.description??null,d.durationMinutes,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]}); } catch(e){ if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)} });
router.post("/listening/sections/:sectionId/audio", requireAuth, requireRole(...contentRoles), upload.single("audio"), async (req,res,next) => { try { if(!req.file)return res.status(400).json({message:"An audio file is required"}); const r=await pool.query("UPDATE listening_sections SET audio_url=$1 WHERE id=$2 RETURNING id,audio_url AS \"audioUrl\"",[`/uploads/${req.file.filename}`,req.params.sectionId]); if(!r.rowCount)return res.status(404).json({message:"Section not found"});res.json({section:r.rows[0]}); }catch(e){next(e)} });
router.post("/listening/tests/:testId/sections", requireAuth, requireRole(...contentRoles), async (req,res,next)=>{try{const d=z.object({sectionNumber:z.number().int().min(1).max(4),title:z.string().optional(),instructions:z.string().optional()}).parse(req.body);const r=await pool.query("INSERT INTO listening_sections(test_id,section_number,title,instructions) VALUES($1,$2,$3,$4) RETURNING id,section_number AS \"sectionNumber\"",[req.params.testId,d.sectionNumber,d.title??null,d.instructions??null]);res.status(201).json({section:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/listening/sections/:sectionId/questions", requireAuth, requireRole(...contentRoles), async(req,res,next)=>{try{const q=question.parse(req.body);const r=await pool.query("INSERT INTO listening_questions(section_id,question_number,question_type,prompt,options,accepted_answers,explanation,points) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[req.params.sectionId,q.questionNumber,q.questionType,q.prompt,JSON.stringify(q.options),JSON.stringify(q.acceptedAnswers),q.explanation??null,q.points]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/listening/tests/:testId", requireAuth, async(req:AuthenticatedRequest,res,next)=>{try{const published=isStaff(req)?"":"AND t.is_published=TRUE";const r=await pool.query(`SELECT t.id,t.title,t.description,t.duration_minutes AS "durationMinutes",COALESCE(json_agg(json_build_object('id',s.id,'sectionNumber',s.section_number,'title',s.title,'audioUrl',s.audio_url,'instructions',s.instructions,'questions',(SELECT COALESCE(json_agg(json_build_object('id',q.id,'questionNumber',q.question_number,'questionType',q.question_type,'prompt',q.prompt,'options',q.options,'points',q.points) ORDER BY q.question_number),'[]') FROM listening_questions q WHERE q.section_id=s.id)) ORDER BY s.section_number) FILTER(WHERE s.id IS NOT NULL),'[]') AS sections FROM listening_tests t LEFT JOIN listening_sections s ON s.test_id=t.id WHERE t.id=$1 ${published} GROUP BY t.id`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});

async function submitObjective(kind:"listening"|"reading", req:AuthenticatedRequest,res:any,next:any){try{const d=answerPayload.parse(req.body);const id=req.params.testId;const table=`${kind}_tests`, qTable=`${kind}_questions`, attemptTable=`${kind}_attempts`, answerTable=`${kind}_answers`;const available=await pool.query(`SELECT q.id,q.accepted_answers,q.points FROM ${qTable} q JOIN ${kind === "listening" ? "listening_sections s ON q.section_id=s.id" : "reading_passages s ON q.passage_id=s.id"} JOIN ${table} t ON s.test_id=t.id WHERE t.id=$1 AND t.is_published=TRUE`,[id]);if(!available.rowCount)return res.status(404).json({message:"Published test not found"});const map=new Map(available.rows.map(q=>[q.id,q]));const seen=new Set<string>();const validAnswers=d.answers.filter(a=>{if(!map.has(a.questionId)||seen.has(a.questionId))return false;seen.add(a.questionId);return true;});const client=await pool.connect();try{await client.query("BEGIN");const a=await client.query(`INSERT INTO ${attemptTable}(user_id,test_id,status,submitted_at,raw_score,total_points) VALUES($1,$2,'submitted',NOW(),0,$3) RETURNING id`,[req.user!.id,id,available.rows.reduce((n,q)=>n+q.points,0)]);let score=0;for(const input of validAnswers){const q=map.get(input.questionId)!;const correct=q.accepted_answers.some((x:string)=>normalize(x)===normalize(input.answer));if(correct)score+=q.points;await client.query(`INSERT INTO ${answerTable}(attempt_id,question_id,answer,is_correct) VALUES($1,$2,$3,$4)`,[a.rows[0].id,input.questionId,JSON.stringify(input.answer),correct])}await client.query(`UPDATE ${attemptTable} SET raw_score=$1 WHERE id=$2`,[score,a.rows[0].id]);await client.query("COMMIT");res.status(201).json({attempt:{id:a.rows[0].id,rawScore:score,totalPoints:available.rows.reduce((n,q)=>n+q.points,0)}})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}}
router.post("/listening/tests/:testId/submit",requireAuth,(req,res,next)=>submitObjective("listening",req,res,next));

router.get("/reading/tests",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,description,duration_minutes AS "durationMinutes" FROM reading_tests ${where} ORDER BY created_at DESC`);res.json({tests:r.rows})}catch(e){next(e)}});
router.post("/reading/tests",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=test.parse(req.body);const r=await pool.query("INSERT INTO reading_tests(title,description,duration_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id,title",[d.title,d.description??null,d.durationMinutes,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/reading/tests/:testId/passages",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const d=z.object({passageNumber:z.number().int().min(1).max(3),title:z.string().min(1),body:z.string().min(1)}).parse(req.body);const r=await pool.query("INSERT INTO reading_passages(test_id,passage_number,title,body) VALUES($1,$2,$3,$4) RETURNING id",[req.params.testId,d.passageNumber,d.title,d.body]);res.status(201).json({passage:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/reading/passages/:passageId/questions",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const q=question.parse(req.body);const r=await pool.query("INSERT INTO reading_questions(passage_id,question_number,question_type,prompt,options,accepted_answers,explanation,points) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[req.params.passageId,q.questionNumber,q.questionType,q.prompt,JSON.stringify(q.options),JSON.stringify(q.acceptedAnswers),q.explanation??null,q.points]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/reading/tests/:testId",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const publication=isStaff(req)?"":"AND t.is_published=TRUE";const r=await pool.query(`SELECT t.id,t.title,t.description,t.duration_minutes AS "durationMinutes",COALESCE(json_agg(json_build_object('id',p.id,'passageNumber',p.passage_number,'title',p.title,'body',p.body,'questions',(SELECT COALESCE(json_agg(json_build_object('id',q.id,'questionNumber',q.question_number,'questionType',q.question_type,'prompt',q.prompt,'options',q.options,'points',q.points) ORDER BY q.question_number),'[]') FROM reading_questions q WHERE q.passage_id=p.id)) ORDER BY p.passage_number) FILTER(WHERE p.id IS NOT NULL),'[]') AS passages FROM reading_tests t LEFT JOIN reading_passages p ON p.test_id=t.id WHERE t.id=$1 ${publication} GROUP BY t.id`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});
router.post("/reading/tests/:testId/submit",requireAuth,(req,res,next)=>submitObjective("reading",req,res,next));

router.get("/writing/tasks",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,task_type AS "taskType",category,prompt,visual_url AS "visualUrl",time_limit_minutes AS "timeLimitMinutes" FROM writing_tasks ${where} ORDER BY created_at DESC`);res.json({tasks:r.rows})}catch(e){next(e)}});
router.post("/writing/tasks",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({title:z.string().min(3),taskType:z.enum(["task_1","task_2"]),category:z.string().min(2),prompt:z.string().min(10),visualUrl:z.string().url().nullable().optional(),timeLimitMinutes:z.number().int().min(5).max(90).default(40),isPublished:z.boolean().default(false)}).parse(req.body);const r=await pool.query("INSERT INTO writing_tasks(title,task_type,category,prompt,visual_url,time_limit_minutes,is_published,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[d.title,d.taskType,d.category,d.prompt,d.visualUrl??null,d.timeLimitMinutes,d.isPublished,req.user!.id]);res.status(201).json({task:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/writing/tasks/:taskId/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({responseText:z.string().min(1).max(20000)}).parse(req.body);const visible=await pool.query("SELECT 1 FROM writing_tasks WHERE id=$1 AND is_published=TRUE",[req.params.taskId]);if(!visible.rowCount)return res.status(404).json({message:"Task not found"});const count=d.responseText.trim().split(/\s+/).filter(Boolean).length;const r=await pool.query("INSERT INTO writing_attempts(user_id,task_id,response_text,word_count) VALUES($1,$2,$3,$4) RETURNING id,word_count AS \"wordCount\",submitted_at AS \"submittedAt\"",[req.user!.id,req.params.taskId,d.responseText,count]);res.status(201).json({attempt:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/writing/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const r=await pool.query("SELECT a.id,a.word_count AS \"wordCount\",a.submitted_at AS \"submittedAt\",t.title,t.task_type AS \"taskType\" FROM writing_attempts a JOIN writing_tasks t ON t.id=a.task_id WHERE a.user_id=$1 ORDER BY a.submitted_at DESC",[req.user!.id]);res.json({attempts:r.rows})}catch(e){next(e)}});

router.get("/speaking/tests",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const where=isStaff(req)?"":"WHERE is_published=TRUE";const r=await pool.query(`SELECT id,title,instructions FROM speaking_tests ${where} ORDER BY created_at DESC`);res.json({tests:r.rows})}catch(e){next(e)}});
router.post("/speaking/tests",requireAuth,requireRole(...contentRoles),async(req:AuthenticatedRequest,res,next)=>{try{const d=z.object({title:z.string().min(3),instructions:z.string().nullable().optional(),isPublished:z.boolean().default(false)}).parse(req.body);const r=await pool.query("INSERT INTO speaking_tests(title,instructions,is_published,created_by) VALUES($1,$2,$3,$4) RETURNING id,title",[d.title,d.instructions??null,d.isPublished,req.user!.id]);res.status(201).json({test:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.post("/speaking/tests/:testId/questions",requireAuth,requireRole(...contentRoles),async(req,res,next)=>{try{const d=z.object({part:z.enum(["part_1","part_2","part_3"]),questionNumber:z.number().int().positive(),prompt:z.string().min(1),cuePoints:z.array(z.string()).default([]),preparationSeconds:z.number().int().min(0).max(300).default(0),responseSeconds:z.number().int().min(15).max(600).default(60)}).parse(req.body);const r=await pool.query("INSERT INTO speaking_questions(test_id,part,question_number,prompt,cue_points,preparation_seconds,response_seconds) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id",[req.params.testId,d.part,d.questionNumber,d.prompt,JSON.stringify(d.cuePoints),d.preparationSeconds,d.responseSeconds]);res.status(201).json({question:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:e.issues[0].message});next(e)}});
router.get("/speaking/tests/:testId",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const publication=isStaff(req)?"":"AND is_published=TRUE";const r=await pool.query(`SELECT id,title,instructions,(SELECT COALESCE(json_agg(json_build_object('id',q.id,'part',q.part,'questionNumber',q.question_number,'prompt',q.prompt,'cuePoints',q.cue_points,'preparationSeconds',q.preparation_seconds,'responseSeconds',q.response_seconds) ORDER BY q.part,q.question_number),'[]') FROM speaking_questions q WHERE q.test_id=speaking_tests.id) AS questions FROM speaking_tests WHERE id=$1 ${publication}`,[req.params.testId]);if(!r.rowCount)return res.status(404).json({message:"Test not found"});res.json({test:r.rows[0]})}catch(e){next(e)}});
router.post("/speaking/tests/:testId/attempts",requireAuth,upload.single("audio"),async(req:AuthenticatedRequest,res,next)=>{try{const questionId=z.string().uuid().parse(req.body.questionId);const test=await pool.query("SELECT 1 FROM speaking_tests WHERE id=$1 AND is_published=TRUE",[req.params.testId]);if(!test.rowCount)return res.status(404).json({message:"Test not found"});const audioUrl=req.file?`/uploads/${req.file.filename}`:null;const r=await pool.query("INSERT INTO speaking_attempts(user_id,test_id,question_id,audio_url,duration_seconds) VALUES($1,$2,$3,$4,$5) RETURNING id,audio_url AS \"audioUrl\",submitted_at AS \"submittedAt\"",[req.user!.id,req.params.testId,questionId,audioUrl,Number(req.body.durationSeconds)||null]);res.status(201).json({attempt:r.rows[0]})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({message:"A valid question is required"});next(e)}});
router.get("/speaking/attempts",requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const r=await pool.query("SELECT a.id,a.audio_url AS \"audioUrl\",a.submitted_at AS \"submittedAt\",q.part,q.prompt FROM speaking_attempts a LEFT JOIN speaking_questions q ON q.id=a.question_id WHERE a.user_id=$1 ORDER BY a.submitted_at DESC",[req.user!.id]);res.json({attempts:r.rows})}catch(e){next(e)}});
export default router;
