import express from "express";
import helmet from "helmet";
import cors from "cors";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import { config } from "./config.js";
import authRoutes from "./routes/auth.routes.js";
import profileRoutes from "./routes/profile.routes.js";
import practiceRoutes from "./routes/practice.routes.js";
import evaluationRoutes from "./routes/evaluation.routes.js";
import coachRoutes from "./routes/coach.routes.js";
import adminRoutes from "./routes/admin.routes.js";
import betaRoutes from "./routes/beta.routes.js";
import communityRoutes from "./routes/community.routes.js";
import reportRoutes from "./routes/report.routes.js";
import privacyRoutes from "./routes/privacy.routes.js";
import qaRoutes from "./routes/qa.routes.js";
import libraryRoutes from "./routes/library.routes.js";
import toolsRoutes from "./routes/tools.routes.js";
import { errorHandler, notFound } from "./middleware/error-handler.js";
import { requireTrustedOrigin } from "./middleware/request-security.js";

export const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(cors({ origin: config.clientUrl, credentials: true }));
app.use(express.json({ limit: "100kb" }));
app.use(cookieParser());
app.use(requireTrustedOrigin);
app.use("/uploads", express.static("uploads"));
app.get("/", (_req, res) => res.json({ message: "IELTS AI Coach API is running", health: "/health", webClient: config.clientUrl }));
app.get("/health", (_req, res) => res.json({ status: "ok" }));
app.use("/api/auth", rateLimit({ windowMs: 15 * 60 * 1000, limit: 20, skip: req => !["/login", "/register"].includes(req.path), standardHeaders: "draft-7", legacyHeaders: false }), authRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/practice", practiceRoutes);
app.use("/api/evaluations", evaluationRoutes);
app.use("/api/coach", coachRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/beta", betaRoutes);
app.use("/api/community", communityRoutes);
app.use("/api/reports", reportRoutes);
app.use("/api/privacy", privacyRoutes);
app.use("/api/qa", qaRoutes);
app.use("/api/library", libraryRoutes);
app.use("/api/tools", toolsRoutes);
app.use(notFound); app.use(errorHandler);
