"use client";
import { useEffect, useRef, useState } from "react";

const skills = [
  { name: "Writing", icon: "✎", color: "blue", title: "One step forward with every response.", description: "Practise Task 1 and Task 2, save your responses and review your work. AI feedback becomes available when a provider is configured.", tags: ["Task 1 & Task 2", "Band estimates", "Detailed feedback"] },
  { name: "Speaking", icon: "♬", color: "green", title: "Build confidence in your own voice.", description: "Choose a prompt, rehearse aloud or record an answer, and build a regular speaking habit. AI evaluation requires a configured provider.", tags: ["Part 1, 2 & 3", "Record answers", "AI evaluation"] },
  { name: "Reading", icon: "▤", color: "purple", title: "Read with purpose. Find the evidence.", description: "Read original passages and answer different question types. Practise with a timer, then review your score and explanations.", tags: ["Practice passages", "Timed practice", "Instant scoring"] },
  { name: "Listening", icon: "♫", color: "orange", title: "Listen closely. Notice the details.", description: "Try browser-voice listening exercises, check your answers and prepare for the next session. All four skills in one workspace.", tags: ["Audio practice", "Section-based tests", "Answer review"] },
];
const faqs = [
  ["How can IELTS AI Coach help?", "Practise all four skills, follow a personal study plan, review vocabulary and track your progress. Writing and speaking AI feedback requires a configured provider."],
  ["Do I need to pay to start?", "The core practice tools and video library are free. Create an account and set your learning goals to begin."],
  ["Are AI band estimates official?", "No. AI feedback and band estimates are learning aids, not official IELTS results or guarantees. Short exercise scores are not IELTS bands."],
  ["Can I use it on my phone?", "Yes. Use a phone, tablet or computer. Recording a speaking answer requires your browser’s microphone permission."],
  ["How is my study plan created?", "Set your starting level, target band, exam date and study time. Your plan prioritises your chosen weak skills and preserves completed work."],
];

function Preview({ skill }: { skill: number }) {
  return <div className={`coach-preview ${skills[skill].color}`} key={skill}>
    <div className="preview-top"><span><i /> {skills[skill].name} workspace</span><span className="sample-label">SAMPLE PREVIEW</span></div>
    {skill === 0 ? <><div className="preview-score"><div><small>Task 2 · Essay feedback</small><h3>A little feedback.<br />A big step forward.</h3></div><div className="band-circle"><strong>7.0</strong><small>EST. BAND</small></div></div><div className="score-bars">{[["Task response", "78%"], ["Coherence & cohesion", "68%"], ["Lexical resource", "82%"], ["Grammar", "74%"]].map(([label,width]) => <div key={label}><span>{label}</span><div><i style={{width}} /></div></div>)}</div><p className="preview-note">✦ Start each paragraph with a clear topic sentence.</p></> : skill === 1 ? <><div className="record-orb">♬</div><h3 className="center">Your next conversation starts here.</h3><p className="cue">Describe a place you would love to visit.</p><div className="wave" aria-hidden="true">{Array.from({length:25},(_,i)=><i key={i} style={{animationDelay:`${i*.09}s`,height:`${12+(i*13)%32}px`}} />)}</div><p className="center subtle">Record. Reflect. Try again.</p></> : skill === 2 ? <><small>READING · PRACTICE PASSAGE</small><h3>The cities of tomorrow</h3><p className="reading-copy">As cities grow, green spaces play an increasingly important role in the lives of their residents. Urban gardens offer more than a place to relax…</p><div className="reading-question">Green spaces can benefit city residents.<div><span className="selected-answer">True ✓</span><span>False</span><span>Not given</span></div></div></> : <><div className="record-orb">♫</div><h3 className="center">Listen closely. Learn confidently.</h3><div className="audio-track"><span>▶</span><div><i /></div><small>01:23 / 03:05</small></div><div className="reading-question">Complete the notes<span className="answer-line">Meeting point: <b>main entrance</b></span><span className="answer-line">Group size: <b>12 people</b></span></div></>}
  </div>;
}

export function Landing({ start, login }: { start: () => void; login: () => void }) {
  const [menu, setMenu] = useState(false);
  const [skill, setSkill] = useState(0);
  const [motion, setMotion] = useState(true);
  const root = useRef<HTMLElement>(null);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("visible"); observer.unobserve(entry.target); } }), { threshold: .08 });
    root.current?.querySelectorAll(".reveal").forEach(node => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  return <main ref={root} className={`coach-landing ${motion ? "" : "motion-paused"}`} lang="en">
    <header className="coach-header"><div className="coach-nav wrap"><a className="coach-brand" href="#home" aria-label="IELTS AI Coach home">IELTS<span>coach</span><sup>AI</sup></a><nav className={menu ? "nav-links is-open" : "nav-links"} aria-label="Main navigation"><a href="#practice" onClick={()=>setMenu(false)}>Practice</a><a href="#features" onClick={()=>setMenu(false)}>AI Features</a><a href="#study-plan" onClick={()=>setMenu(false)}>Study plan</a><a href="#faq" onClick={()=>setMenu(false)}>FAQ</a></nav><div className="nav-actions"><span className="country">🌐 English</span><button className="login-link" onClick={login}>Sign in</button><button className="coach-button small" onClick={start}>Start for free <span>↗</span></button><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu ? "✕" : "☰"}</button></div></div></header>
    <section id="home" className="coach-hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-glow" aria-hidden="true"/><div className="wrap hero-content"><div className="eyebrow hero-enter"><i/> Your personal IELTS preparation workspace</div><h1 className="hero-enter">Big dreams start with<br/> <span className="gradient-text">your next small step.</span></h1><p className="hero-description hero-enter">Practice, a personal study plan and progress tracking — all in one place.<br className="desktop-break"/> Move forward on your IELTS journey, at your own pace.</p><div className="hero-buttons hero-enter"><button className="coach-button" onClick={start}>Start free practice <span>↗</span></button><a className="coach-button outline" href="#practice"><span className="play-icon">▶</span> Explore the platform</a></div><div className="hero-assurances hero-enter"><span>✓ Free practice</span><span>✓ No credit card required</span><span>✓ Learn in your own time</span></div>
    <div className="hero-product hero-enter"><div className="product-title"><span><i/><i/><i/></span><small>YOUR PERSONAL IELTS WORKSPACE</small><span className="live-label">● Ready to learn</span></div><div className="product-body"><aside><div className="mini-brand">IELTS<span>coach</span></div><div className="mini-nav active">◫ <span>Overview</span></div><div className="mini-nav">◷ <span>Study plan</span></div><div className="mini-nav">✎ <span>Practice</span></div><div className="mini-nav">↗ <span>Progress</span></div><div className="sidebar-bottom">ONE DAY.<br/>ONE STEP CLOSER.</div></aside><div className="product-main"><div className="product-greeting"><div><small>LET’S MAKE TODAY COUNT</small><h3>Your next band starts here <span>✦</span></h3></div><span className="avatar">You</span></div><div className="mock-stats"><div><span>Target band</span><strong>7.5 <small>↗ Your goal</small></strong></div><div><span>Daily practice</span><strong>30 <small>minutes</small></strong></div><div><span>Skills to explore</span><strong>04 <small>all in one</small></strong></div></div><div className="mock-bottom"><div className="today-plan"><div className="panel-heading"><b>Today’s focus</b><span>Personal study plan</span></div>{[["✎","Writing practice","Build a stronger introduction","15 min"],["♬","Speaking session","Describe a memorable journey","10 min"],["▤","Vocabulary review","Make new words stick","5 min"]].map(([icon,title,desc,time])=><div className="plan-row" key={title}><i>{icon}</i><div><b>{title}</b><small>{desc}</small></div><span>{time}</span></div>)}</div><div className="progress-card"><span>CONSISTENCY IS EVERYTHING</span><h4>Small steps.<br/>Real progress.</h4><div className="mini-chart" aria-hidden="true">{[26,39,35,57,64,74,95].map((h,i)=><i key={i} style={{height:`${h}%`,animationDelay:`${i*.12}s`}} />)}</div><small>Illustrative progress preview</small></div></div></div></div><div className="floating-feedback"><span>✦</span><div><b>A clearer way forward</b><small>Practice → Feedback → Progress</small></div></div></div></div></section>
    <div className="feature-ticker"><div className="ticker-track">{[0,1].map(n=><div aria-hidden={n===1} key={n}>{["AI WRITING FEEDBACK","SPEAKING PRACTICE","PERSONAL STUDY PLAN","ALL FOUR SKILLS","VOCABULARY BUILDER","PROGRESS TRACKING"].map(t=><span key={t}>{t}<i>✦</i></span>)}</div>)}</div><button onClick={()=>setMotion(!motion)} aria-label={motion ? "Pause animations" : "Play animations"}>{motion ? "Ⅱ" : "▶"}</button></div>
    <section id="features" className="section wrap"><div className="section-heading reveal"><span className="section-label">A LITTLE CLARITY. A LOT MORE CONFIDENCE.</span><h2>Understand your next step.<br/><span>Build confidence as you go.</span></h2><p>Know what to study, how to practise and where to focus your review.</p></div><div className="feature-cards">{[["01","✎","Make your writing clearer.","Save written responses and review your ideas. AI feedback requires a configured provider.","Writing feedback","#practice"],["02","♬","Make speaking a regular habit.","Choose a cue card, rehearse your answer and record it when you are ready.","Speaking practice","#practice"],["03","◷","Spend less time planning.","Follow daily tasks based on your goals, priority skills and available time.","Your daily roadmap","#study-plan"]].map(([n,icon,title,desc,label,href])=><article className="feature-card reveal" key={n}><div className="feature-card-top"><span>{icon}</span><small>{n} /</small></div><h3>{title}</h3><p>{desc}</p><a href={href}>{label} <span>↗</span></a></article>)}</div></section>
    <section id="practice" className="practice-section section"><div className="wrap"><div className="section-heading reveal"><span className="section-label">FOUR SKILLS. ONE WORKSPACE.</span><h2>Whichever skill you focus on,<br/><span>keep your learning together.</span></h2><p>Choose a skill to explore a sample workspace.</p></div><div className="skill-tabs" role="tablist" aria-label="Practice skills">{skills.map((s,i)=><button key={s.name} role="tab" id={`skill-tab-${i}`} aria-controls="skill-preview" aria-selected={skill===i} tabIndex={skill===i?0:-1} className={skill===i?"active":""} onClick={()=>setSkill(i)} onKeyDown={e=>{if(["ArrowRight","ArrowLeft","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?0:e.key==="End"?3:(i+(e.key==="ArrowRight"?1:3))%4;setSkill(next);document.getElementById(`skill-tab-${next}`)?.focus();}}}><span>{s.icon}</span>{s.name}</button>)}</div><div className={`skill-panel ${skills[skill].color}`} id="skill-preview" role="tabpanel" aria-labelledby={`skill-tab-${skill}`}><div className="skill-copy"><span className="section-label">{skills[skill].name.toUpperCase()} PRACTICE</span><h3>{skills[skill].title}</h3><p>{skills[skill].description}</p><div className="skill-tags">{skills[skill].tags.map(t=><span key={t}>✓ {t}</span>)}</div><button className="text-button" onClick={start}>Start practising <span>↗</span></button></div><Preview skill={skill}/></div></div></section>
    <section id="study-plan" className="section wrap"><div className="section-heading reveal"><span className="section-label">YOUR JOURNEY, SIMPLIFIED</span><h2>Three simple steps.<br/><span>A clearer preparation routine.</span></h2></div><div className="steps-grid">{[["01","Set your destination","Add your starting level, target band and exam date to your profile.","◎"],["02","Follow your plan","Work through daily activities built around your priority skills and study time.","▦"],["03","Review your progress","Check your answers, track progress and bring what you learn to the next session.","↗"]].map(([n,title,desc,icon])=><article className="step reveal" key={n}><div><span>{n}</span><i>{icon}</i></div><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
    <section className="habit-section"><div className="wrap habit-grid"><div className="reveal"><span className="section-label">SHOW UP FOR YOUR FUTURE</span><h2>A little at a time.<br/><span className="gradient-text">A little better every day.</span></h2><p>You do not need to do everything at once. One writing task, a few words and a little speaking practice can build a lasting habit.</p><button className="coach-button" onClick={start}>Start my preparation <span>↗</span></button></div><div className="habit-card reveal"><div className="panel-heading"><b>Your weekly rhythm</b><span>✦ KEEP GOING</span></div><div className="week-days">{["Sat","Sun","Mon","Tue","Wed","Thu","Fri"].map((day,i)=><div key={day}><span>{day}</span><i className={i<5?"done":""}>{i<5?"✓":"·"}</i></div>)}</div><div className="habit-word"><small>ONE WORD AT A TIME</small><h3>Perseverance</h3><p>Keep going, even when it feels difficult.</p></div><small className="subtle">Sample activity · Your progress appears after practice</small></div></div></section>
    <section id="faq" className="section wrap faq-grid"><div className="reveal"><span className="section-label">LET’S CLEAR THINGS UP</span><h2>Have a question?<br/><span>Start here.</span></h2><p>A few things to know before you begin.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="final-cta wrap reveal"><span className="section-label">YOUR NEXT CHAPTER STARTS HERE</span><h2>Your dream.<br/>Your preparation partner.</h2><p>Begin your IELTS journey with one small step.</p><button className="coach-button" onClick={start}>Let’s get started <span>↗</span></button><small>Free to start. Built around you.</small></section>
    <footer className="coach-footer wrap"><div><a className="coach-brand" href="#home">IELTS<span>coach</span><sup>AI</sup></a><p>Your goal. Your pace. Your IELTS coach.</p></div><div className="footer-links"><a href="#practice">Practice</a><a href="#study-plan">Study plan</a><a href="#faq">FAQ</a><button onClick={login}>Sign in ↗</button></div><div className="footer-bottom"><span>© {new Date().getFullYear()} IELTS AI Coach</span><span>Independent IELTS practice platform. Practice scores are estimates.</span></div></footer>
  </main>;
}
