"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
import {StudyCalendar,type StudyTask} from "./study-calendar";
type Roadmap={today:string;profile:{currentLevel:number|null;targetBand:number|null;examDate:string|null;startDate:string|null;endDate:string|null;dailyStudyMinutes:number|null;complete:boolean};tasks:StudyTask[]};
const taskLink=(task:StudyTask)=>task.href??(["writing","reading","listening","speaking"].includes(task.taskType)?"/practice/"+task.taskType:"/dashboard/"+(task.taskType==="vocabulary"?"vocabulary":"grammar"));
const dateOffset=(date:string,n:number)=>new Date(Date.parse(date+"T12:00:00Z")+n*86400000).toISOString().slice(0,10);
export function StudyCoach(){
  const [data,setData]=useState<Roadmap|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
  const load=async()=>setData(await api<Roadmap>("/api/coach/plan/roadmap"));
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const generate=async()=>{setBusy("plan");setError("");setMessage("");try{const result=await api<{addedTasks:number;days:number}>("/api/coach/plan/roadmap",{method:"POST",body:"{}"});await load();setMessage(result.addedTasks+" new activities scheduled through the day before your exam. Existing tasks and completed progress were preserved.");}catch(e){setError(e instanceof Error?e.message:"Could not create your roadmap.");}finally{setBusy("");}};
  const update=async(task:StudyTask,status:StudyTask["status"])=>{setBusy(task.id);setError("");try{await api("/api/coach/plan/"+task.id,{method:"PATCH",body:JSON.stringify({status})});await load();setMessage(status==="completed"?"Activity completed. Your progress is saved.":status==="skipped"?"Activity skipped. You can restore it with Undo.":"Activity restored to pending.");}catch(e){setError(e instanceof Error?e.message:"Could not save progress.");}finally{setBusy("");}};
  const renderTask=(task:StudyTask)=><article className="roadmap-task" key={task.id}><div className="roadmap-task-copy"><small className="library-eyebrow capitalize">{task.taskType} · {task.duration} MIN · {task.phase??"Daily practice"}</small><h3>{task.title??task.taskType[0].toUpperCase()+task.taskType.slice(1)+" practice"}</h3><p>{task.taskDescription}</p><details><summary>Why this activity?</summary><p>{task.reason??"This saved activity supports your chosen study time and priority skills. Work through it, then review what you learned."}</p></details><span className="roadmap-status">{task.status==="completed"?"✓ Completed":task.status==="skipped"?"Skipped":"Pending"}</span></div><div className="feature-actions"><a className="workspace-primary-button" href={taskLink(task)}>{task.status==="completed"?"Review activity":"Open activity"} →</a>{task.status==="pending"?<><button className="workspace-button" disabled={!!busy} onClick={()=>update(task,"completed")}>{busy===task.id?"Saving…":"Mark complete"}</button><button className="workspace-button" disabled={!!busy} onClick={()=>update(task,"skipped")}>Skip</button></>:<button className="workspace-button" disabled={!!busy} onClick={()=>update(task,"pending")}>{busy===task.id?"Saving…":"Undo"}</button>}</div></article>;
  const tasks=data?.tasks??[],todayTasks=tasks.filter(t=>t.date===data?.today),mission=todayTasks.find(t=>t.status==="pending");
  const done=tasks.filter(t=>t.status==="completed").length,percent=tasks.length?Math.round(done/tasks.length*100):0;
  const today=data?.today??new Date().toISOString().slice(0,10),weekday=new Date(today+"T12:00:00Z").getUTCDay(),weekStart=dateOffset(today,-weekday),weekEnd=dateOffset(weekStart,7),week=tasks.filter(t=>t.date>=weekStart&&t.date<weekEnd);
  const completedDays=new Set(tasks.filter(t=>t.status==="completed"&&t.date<=today).map(t=>t.date));let streak=0,cursor=completedDays.has(today)?today:dateOffset(today,-1);while(completedDays.has(cursor)){streak++;cursor=dateOffset(cursor,-1);}
  return <section className="feature-page"><header className="feature-section-heading"><div><span className="library-eyebrow">YOUR PERSONAL ROADMAP</span><h1 className="mt-3 text-3xl font-bold">Your study plan</h1><p className="feature-hint">Learn the foundations, practise each skill, and review before exam day.</p></div><div className="feature-actions"><a className="workspace-button" href="/onboarding">Edit learning profile</a><button className="workspace-primary-button" disabled={!!busy||!data} onClick={generate}>{busy==="plan"?"Building roadmap…":data?.profile.startDate?"Fill missing roadmap days":"Build exam roadmap"}</button></div></header>
  {error&&<div role="alert" className="feature-notice error">{error} <button onClick={()=>{setError("");load().catch(e=>setError(e.message));}}>Reload</button> <a href="/onboarding">Edit profile</a></div>}{message&&<p role="status" className="feature-notice">{message}</p>}{!data&&!error&&<p role="status">Loading your roadmap…</p>}
  {data&&<><div className="feature-stats four">{[["Starting band",data.profile.currentLevel??"Not set","Self-reported starting point"],["Target band",data.profile.targetBand??"Not set","Your learning goal"],["Study streak",streak+" days","Days with at least one completed activity"],["Plan progress",done+"/"+tasks.length,percent+"% of scheduled tasks complete"]].map(([label,value,hint])=><article className="workspace-panel" key={label}><p>{label}</p><strong>{value}</strong><small>{hint}</small></article>)}</div>
  <section className="feature-hero"><span className="library-eyebrow">TODAY’S MISSION · {mission?.phase??"GET STARTED"}</span>{mission?<><h2>{mission.title??mission.taskType+" practice"}</h2><p>{mission.taskDescription}</p><div className="feature-actions mt-5"><a className="workspace-primary-button" href={taskLink(mission)}>Start activity →</a><span>{todayTasks.filter(t=>t.status==="completed").length}/{todayTasks.length} activities completed · {todayTasks.reduce((s,t)=>s+t.duration,0)} minutes planned</span></div></>:<><h2>{todayTasks.length?(todayTasks.every(t=>t.status==="completed")?"Today’s plan is complete.":"No pending activities today."):data.profile.complete?"Build your preparation roadmap.":"Set your destination first."}</h2><p>{todayTasks.length?"Your progress is saved. Review completed activities or choose another day in the calendar.":data.profile.complete?"Build a calendar from today through the day before your exam. Lessons link to the free library and practice pages.":"Add your current band, target band, exam date and study time to schedule your learning."}</p><a className="workspace-button mt-5" href="/onboarding">Set learning goals →</a></>}</section>
  <section className="workspace-panel"><div className="feature-section-heading"><h2>This week’s focus</h2><span>{week.filter(t=>t.status==="completed").length}/{week.length} tasks complete · {(week.reduce((s,t)=>s+t.duration,0)/60).toFixed(1)} planned hours</span></div><div className="feature-actions">{[...new Set(week.map(t=>t.taskType))].map(skill=><span className="roadmap-focus capitalize" key={skill}>{skill} × {week.filter(t=>t.taskType===skill).length}</span>)}</div><p className="feature-hint">{data.profile.startDate?data.profile.startDate+" → "+data.profile.endDate+" · "+data.profile.dailyStudyMinutes+" minutes a day":"Only your existing daily activities are shown until you build a roadmap."} Existing activities are preserved when filling missing days. Lessons are practice aids, not a guaranteed band improvement.</p><progress className="roadmap-progress" aria-label="Roadmap completion" value={done} max={tasks.length||1}/></section>
  <StudyCalendar tasks={tasks} today={data.today} renderTask={renderTask}/><p className="feature-hint">Open an activity and work through it, then mark it complete here. Completion is self-reported; simply opening a page does not complete a task.</p></>}
  </section>;
}
