"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
type Task={id:string;date:string;taskType:string;taskDescription:string;duration:number;status:string};
const dateInDhaka=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function StudyCalendar(){
  const today=dateInDhaka(),[month,setMonth]=useState(today.slice(0,7)),[selected,setSelected]=useState(today),[tasks,setTasks]=useState<Task[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{setTasks((await api<{tasks:Task[]}>("/api/coach/plan/history?month="+month)).tasks);}catch(e){setError(e instanceof Error?e.message:"Could not load your calendar.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[month]);
  const move=(offset:number)=>{const date=new Date(month+"-01T12:00:00Z");date.setUTCMonth(date.getUTCMonth()+offset);setMonth(date.toISOString().slice(0,7));setSelected(date.toISOString().slice(0,10));};
  const first=new Date(month+"-01T12:00:00Z"),days=new Date(first.getUTCFullYear(),first.getUTCMonth()+1,0).getUTCDate(),offset=first.getUTCDay(),daily=tasks.filter(t=>t.date===selected);
  return <section className="workspace-panel mt-6"><div className="feature-section-heading"><h2>Your study calendar</h2><div className="feature-actions"><button className="workspace-button" aria-label="Previous month" onClick={()=>move(-1)}>←</button><b>{first.toLocaleDateString("en-GB",{month:"long",year:"numeric",timeZone:"UTC"})}</b><button className="workspace-button" aria-label="Next month" onClick={()=>move(1)}>→</button><button className="workspace-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today);}}>Today</button></div></div><p className="feature-hint">Select a day to see its saved plan. Only generated plans appear here; an empty date is not a missed task.</p>{error&&<p role="alert" className="feature-notice error">{error} <button onClick={load}>Retry</button></p>}{loading&&<p role="status">Loading saved plans…</p>}<div className="study-calendar" aria-label="Saved study plans">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}{Array.from({length:offset},(_,i)=><span key={"blank-"+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+"-"+String(i+1).padStart(2,"0"),items=tasks.filter(t=>t.date===date),complete=items.length>0&&items.every(t=>t.status==="completed");return <button key={date} aria-label={date+": "+items.length+" tasks"+(complete?", completed":"")} aria-pressed={selected===date} className={(selected===date?"selected ":"")+(date===today?"today ":"")+(complete?"completed":"")} onClick={()=>setSelected(date)}><b>{i+1}</b><small>{items.length?items.length+" tasks":"—"}</small></button>;})}</div><section className="calendar-day"><h3>{selected===today?"Today’s activities":selected}</h3>{daily.length?daily.map(t=><article key={t.id}><div><b className="capitalize">{t.taskType} · {t.duration} min</b><p>{t.taskDescription}</p></div><span>{t.status==="completed"?"✓ Completed":t.status==="skipped"?"Skipped":"Pending"}</span></article>):<p>No saved plan for this date. Generate today’s plan above to get started.</p>}</section></section>;
}
