"use client";
import {useState,type ReactNode} from "react";
export type StudyTask={id:string;date:string;taskType:string;taskDescription:string;duration:number;status:"pending"|"completed"|"skipped";title?:string|null;href?:string|null;reason?:string|null;phase?:string|null};
export function StudyCalendar({tasks,today,renderTask}:{tasks:StudyTask[];today:string;renderTask:(task:StudyTask)=>ReactNode}){
  const [month,setMonth]=useState(today.slice(0,7)),[selected,setSelected]=useState(today);
  const move=(offset:number)=>{const date=new Date(month+"-01T12:00:00Z");date.setUTCMonth(date.getUTCMonth()+offset);setMonth(date.toISOString().slice(0,7));setSelected(date.toISOString().slice(0,10));};
  const first=new Date(month+"-01T12:00:00Z"),days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),offset=first.getUTCDay(),daily=tasks.filter(t=>t.date===selected);
  return <section className="workspace-panel mt-6"><div className="feature-section-heading"><h2>Your study calendar</h2><div className="feature-actions"><button className="workspace-button" aria-label="Previous month" onClick={()=>move(-1)}>←</button><b>{first.toLocaleDateString("en-GB",{month:"long",year:"numeric",timeZone:"UTC"})}</b><button className="workspace-button" aria-label="Next month" onClick={()=>move(1)}>→</button><button className="workspace-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today);}}>Today</button></div></div><p className="feature-hint">Select a day to open its lessons and manage activities. Dates follow Bangladesh time. Green means every task is complete; skipped activities do not count as completed.</p><div className="study-calendar" aria-label="Study roadmap">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}{Array.from({length:offset},(_,i)=><span key={"blank-"+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+"-"+String(i+1).padStart(2,"0"),items=tasks.filter(t=>t.date===date),complete=items.length>0&&items.every(t=>t.status==="completed");return <button key={date} aria-label={date+": "+items.length+" tasks"+(complete?", completed":"")} aria-pressed={selected===date} className={(selected===date?"selected ":"")+(date===today?"today ":"")+(complete?"completed":"")} onClick={()=>setSelected(date)}><b>{i+1}</b><small className="capitalize">{items[0]?.taskType??"—"}</small><small>{items.length?items.filter(t=>t.status==="completed").length+"/"+items.length+" done":""}</small></button>;})}</div><section className="calendar-day"><h3>{selected===today?"Today’s activities":new Date(selected+"T12:00:00Z").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"UTC"})}</h3>{daily.length?<><p className="feature-hint">{daily.reduce((sum,t)=>sum+t.duration,0)} planned minutes · {daily[0].phase??"Saved daily plan"}</p>{daily.map(renderTask)}</>:<p>No scheduled activities for this date. Build your exam roadmap above, or choose a date inside its range.</p>}</section></section>;
}
