"use client";
import {useEffect,useMemo,useState} from "react";
import {api} from "../lib/api";
import {Icon} from "./dashboard";
import {topicDescriptions,topicSlug,vocabularyGuide} from "../lib/vocabulary-guide";
type Word={id:string;word:string;meaning:string;exampleSentence:string;synonyms:string[];difficulty:string;masteryLevel:number;reviewDate:string|null;lastReviewedAt:string|null;topic?:string|null};
type Mode="continue"|"due"|"all";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const topicOf=(w:Word)=>vocabularyGuide[w.word]?.topic??w.topic??"Academic Vocabulary";
const levelOf=(w:Word)=>vocabularyGuide[w.word]?.level??"Intermediate";
export function VocabularyDeck({initialTopic}:{initialTopic?:string}){
  const [words,setWords]=useState<Word[]>([]),[queue,setQueue]=useState<string[]>([]),[index,setIndex]=useState(0),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[level,setLevel]=useState("all"),[view,setView]=useState("cards"),[revealed,setRevealed]=useState(false),[mode,setMode]=useState<Mode>("continue"),[speechWord,setSpeechWord]=useState(""),[showBengali,setShowBengali]=useState(false);
  const load=async()=>{try{const data=await api<{words:Word[]}>("/api/coach/vocabulary");setWords([...data.words].sort((a,b)=>a.word.localeCompare(b.word)));setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load vocabulary.");}finally{setLoaded(true);}};
  useEffect(()=>{load();return()=>{if("speechSynthesis" in window)window.speechSynthesis.cancel();};},[]);
  const topics=useMemo(()=>Array.from(new Set(words.map(topicOf))).sort(),[words]);
  const selected=topics.find(t=>topicSlug(t)===initialTopic);
  const deck=words.filter(w=>topicOf(w)===selected);
  const buildQueue=(nextMode:Mode)=>deck.filter(w=>nextMode==="all"||(nextMode==="due"?(w.reviewDate===null||w.reviewDate<=today()):w.masteryLevel<5)).map(w=>w.id);
  useEffect(()=>{if(selected&&loaded){setQueue(buildQueue("continue"));setIndex(0);setRevealed(false);}},[selected,loaded]);
  const word=words.find(w=>w.id===queue[index]);
  const studied=words.filter(w=>w.lastReviewedAt).length,known=words.filter(w=>w.masteryLevel===5).length;
  const filteredTopics=topics.filter(t=>(category==="all"||category===t)&&words.some(w=>topicOf(w)===t&&(level==="all"||levelOf(w)===level)&&(t+" "+w.word+" "+w.meaning).toLowerCase().includes(query.toLowerCase())));
  const choose=(nextMode:Mode)=>{setMode(nextMode);setQueue(buildQueue(nextMode));setIndex(0);setRevealed(false);setMessage("");};
  const pronounce=(value:string)=>{setError("");if(!("speechSynthesis" in window)){setError("Word pronunciation is not supported in this browser.");return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(value);utterance.lang="en-GB";utterance.rate=.8;utterance.onend=()=>setSpeechWord("");utterance.onerror=(event)=>{if(["canceled","interrupted"].includes(event.error))return;setSpeechWord("");setError("Could not play this browser voice. Try another browser.");};setSpeechWord(value);window.speechSynthesis.speak(utterance);};
  const rate=async(rating:number)=>{if(!word||busy)return;setBusy(true);setError("");try{const data=await api<{progress:{masteryLevel:number;reviewDate:string}}>("/api/coach/vocabulary/"+word.id,{method:"PATCH",body:JSON.stringify({masteryLevel:rating})});setWords(current=>current.map(w=>w.id===word.id?{...w,...data.progress,lastReviewedAt:new Date().toISOString()}:w));setIndex(i=>i+1);setRevealed(false);setMessage("Review saved. Next review: "+data.progress.reviewDate.slice(0,10)+".");}catch(e){setError(e instanceof Error?e.message:"Could not save review.");}finally{setBusy(false);}};
  const details=(w:Word)=>{const guide=vocabularyGuide[w.word];return <><p className="vocab-meaning">{w.meaning}</p>{guide&&showBengali&&<p className="vocab-bengali" lang="bn">{guide.bengali}</p>}<blockquote>{w.exampleSentence}</blockquote>{guide&&<p className="vocab-collocation"><b>Collocations:</b> {guide.collocations.join(" · ")}</p>}<p className="vocab-collocation"><b>Synonyms:</b> {w.synonyms.join(", ")||"No synonyms provided"}</p>{guide?.mistake&&<aside className="vocab-mistake"><b>Common usage tip</b><p>{guide.mistake}</p></aside>}</>;};
  return <section className="feature-page vocabulary-page">
    <header className="tool-header feature-heading"><span className="library-module-icon"><Icon name="book"/></span><div><h1>{selected??"Vocabulary"}</h1><p>{selected?topicDescriptions[selected]??"Learn the meaning, use the word in a sentence, then review your recall.":"Topic-based IELTS vocabulary, Bengali meanings and active recall."}</p></div></header>
    {initialTopic&&loaded&&!selected&&<p role="alert" className="feature-notice">This topic is not available. <a href="/dashboard/vocabulary">Browse topics</a></p>}
    {error&&<p role="alert" className="feature-notice error">{error} <button onClick={load}>Retry</button></p>}
    {!loaded&&<p role="status">Loading vocabulary…</p>}
    {!initialTopic&&<>
      <section className="feature-hero"><span className="library-eyebrow">LEXICAL RESOURCE</span><h2>Make new words part of your everyday English.</h2><p>Explore a topic, reveal meanings and examples, listen to pronunciation, and review words when they are due.</p></section>
      <div className="feature-stats"><article className="workspace-panel"><p>Topics</p><strong>{topics.length}</strong><small>{words.length} published words</small></article><article className="workspace-panel"><p>Mastered</p><strong>{known}</strong><small>{words.length?Math.round(known/words.length*100):0}% of published words</small></article><article className="workspace-panel"><p>Average recall</p><strong>{studied?(words.filter(w=>w.lastReviewedAt).reduce((s,w)=>s+w.masteryLevel,0)/studied).toFixed(1):"—"}</strong><small>{studied} words reviewed · out of 5</small></article></div>
      <div className="feature-section-heading"><h2>Browse topics</h2><span>{filteredTopics.length} of {topics.length} topics</span></div>
      <div className="vocab-filters"><label><span className="sr-only">Search vocabulary topics</span><input className="tool-input" placeholder="Search topics or words…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category<select className="tool-input" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{topics.map(t=><option key={t}>{t}</option>)}</select></label></div>
      <div className="feature-tabs" aria-label="Vocabulary level">{["all","Beginner","Intermediate","Advanced"].map(l=><button key={l} aria-pressed={level===l} className={level===l?"selected":""} onClick={()=>setLevel(l)}>{l==="all"?"All levels":l}</button>)}</div>
      <div className="topic-grid">{filteredTopics.map(t=>{const entries=words.filter(w=>topicOf(w)===t);return <a className="workspace-panel topic-card" key={t} href={"/dashboard/vocabulary/"+topicSlug(t)}><span className="topic-state">{entries.every(w=>w.masteryLevel===5)?"Mastered":entries.some(w=>w.lastReviewedAt)?"In progress":"Not started"}</span><h2>{t}</h2><p>{topicDescriptions[t]??"Build useful vocabulary for IELTS practice."}</p><progress aria-label={t+" mastery"} max={entries.length*5} value={entries.reduce((s,w)=>s+w.masteryLevel,0)}/><span>{entries.filter(w=>w.lastReviewedAt).length} studied · {entries.filter(w=>w.masteryLevel===5).length} known</span><footer><b>{entries.length} words</b><Icon name="arrow"/></footer></a>;})}</div>
      {loaded&&!filteredTopics.length&&<p className="feature-notice">No matching topics. Try another search or level.</p>}
    </>}
    {selected&&<>
      <label className="feature-hint flex items-center gap-3"><input type="checkbox" className="w-auto" checked={showBengali} onChange={e=>setShowBengali(e.target.checked)}/>Show Bengali meanings</label>
      <a className="dashboard-text-link" href="/dashboard/vocabulary">← All vocabulary topics</a>
      <div className="feature-tabs mt-6" aria-label="Vocabulary view"><button aria-pressed={view==="cards"} className={view==="cards"?"selected":""} onClick={()=>setView("cards")}>Flashcards</button><button aria-pressed={view==="list"} className={view==="list"?"selected":""} onClick={()=>setView("list")}>List</button></div>
      <div className="feature-section-heading"><p>{deck.filter(w=>w.lastReviewedAt).length} studied · {deck.filter(w=>w.masteryLevel===5).length} known</p><div className="feature-actions">{(["continue","due","all"] as Mode[]).map(m=><button disabled={busy} className={mode===m?"workspace-primary-button":"workspace-button"} key={m} onClick={()=>choose(m)}>{m==="continue"?"Continue learning":m==="due"?"Review due words":"Study all words"}</button>)}</div></div>
      {view==="list"?<div className="vocabulary-list">{deck.map(w=><article className="workspace-panel" key={w.id}><div className="feature-section-heading"><h2>{w.word}</h2><button className="workspace-button" aria-label={"Pronounce "+w.word} onClick={()=>pronounce(w.word)}>{speechWord===w.word?"Playing…":"🔊"}</button></div><p className="vocab-meta">{vocabularyGuide[w.word]?.part??"word"} · {levelOf(w)} · recall {w.masteryLevel}/5</p>{details(w)}</article>)}</div>:word?<div className="vocab-study"><div className="feature-section-heading"><p>Card {index+1} of {queue.length}</p><span>{Math.round(index/Math.max(queue.length,1)*100)}% reviewed</span></div><progress aria-label="Session progress" max={Math.max(queue.length,1)} value={index}/><article className="workspace-panel vocab-flashcard"><button className="vocab-reveal" aria-expanded={revealed} onClick={()=>setRevealed(!revealed)}><span>{revealed?"HIDE ANSWER":"TAP TO REVEAL"}</span><h2>{word.word}</h2><p>{vocabularyGuide[word.word]?.part??"word"} · {levelOf(word)}</p></button><button className="workspace-button" aria-label={"Pronounce "+word.word} onClick={()=>pronounce(word.word)}>🔊 Listen</button>{revealed&&<div className="vocab-answer">{details(word)}</div>}</article><div className="vocab-ratings">{[[0,"Forgot"],[2,"Almost"],[5,"Knew it"]].map(([n,label])=><button key={n} className="workspace-button" disabled={busy||!revealed} onClick={()=>rate(Number(n))}>{busy?"Saving…":label}</button>)}</div><p className="feature-hint">Reveal the answer before rating. “Knew it” marks the word as mastered; forgotten words return sooner.</p><div className="feature-actions"><button className="workspace-button" disabled={busy||index===0} onClick={()=>{setIndex(index-1);setRevealed(false);}}>← Previous</button><button className="workspace-button" disabled={busy} onClick={()=>{setIndex(index+1);setRevealed(false);}}>Skip →</button></div></div>:<section className="workspace-panel vocab-complete"><h2>{mode==="due"&&!queue.length?"No words are due right now.":"This review session is complete."}</h2><p>Your ratings and next review dates are saved to your account.</p><button className="workspace-primary-button" onClick={()=>choose("all")}>Study all words</button></section>}
    </>}
    <p role="status" aria-live="polite" className="library-status">{message}</p><a className="dashboard-text-link" href="/dashboard/content-library/06-vocabulary">Free vocabulary video lessons →</a><p className="feature-hint">Original starter decks. Browser voices are used for pronunciation; this is not the reference site's full commercial catalogue.</p>
  </section>;
}
