CREATE TYPE practice_status AS ENUM ('in_progress', 'submitted');
CREATE TYPE listening_question_type AS ENUM ('multiple_choice', 'form_completion', 'sentence_completion', 'matching', 'map');
CREATE TYPE reading_question_type AS ENUM ('multiple_choice', 'true_false_not_given', 'yes_no_not_given', 'matching_headings', 'sentence_completion');
CREATE TYPE writing_task_type AS ENUM ('task_1', 'task_2');
CREATE TYPE speaking_part AS ENUM ('part_1', 'part_2', 'part_3');

CREATE TABLE listening_tests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(200) NOT NULL, description TEXT, duration_minutes SMALLINT NOT NULL DEFAULT 30, is_published BOOLEAN NOT NULL DEFAULT FALSE, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE listening_sections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), test_id UUID NOT NULL REFERENCES listening_tests(id) ON DELETE CASCADE, section_number SMALLINT NOT NULL CHECK (section_number BETWEEN 1 AND 4), title VARCHAR(200), audio_url TEXT, instructions TEXT, UNIQUE(test_id, section_number));
CREATE TABLE listening_questions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), section_id UUID NOT NULL REFERENCES listening_sections(id) ON DELETE CASCADE, question_number SMALLINT NOT NULL, question_type listening_question_type NOT NULL, prompt TEXT NOT NULL, options JSONB NOT NULL DEFAULT '[]', accepted_answers JSONB NOT NULL DEFAULT '[]', explanation TEXT, points SMALLINT NOT NULL DEFAULT 1 CHECK (points > 0), UNIQUE(section_id, question_number));
CREATE TABLE listening_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, test_id UUID NOT NULL REFERENCES listening_tests(id), status practice_status NOT NULL DEFAULT 'in_progress', started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), submitted_at TIMESTAMPTZ, raw_score SMALLINT, total_points SMALLINT);
CREATE TABLE listening_answers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), attempt_id UUID NOT NULL REFERENCES listening_attempts(id) ON DELETE CASCADE, question_id UUID NOT NULL REFERENCES listening_questions(id), answer JSONB, is_correct BOOLEAN, UNIQUE(attempt_id, question_id));

CREATE TABLE reading_tests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(200) NOT NULL, description TEXT, duration_minutes SMALLINT NOT NULL DEFAULT 60, is_published BOOLEAN NOT NULL DEFAULT FALSE, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE reading_passages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), test_id UUID NOT NULL REFERENCES reading_tests(id) ON DELETE CASCADE, passage_number SMALLINT NOT NULL CHECK (passage_number BETWEEN 1 AND 3), title VARCHAR(300) NOT NULL, body TEXT NOT NULL, UNIQUE(test_id, passage_number));
CREATE TABLE reading_questions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), passage_id UUID NOT NULL REFERENCES reading_passages(id) ON DELETE CASCADE, question_number SMALLINT NOT NULL, question_type reading_question_type NOT NULL, prompt TEXT NOT NULL, options JSONB NOT NULL DEFAULT '[]', accepted_answers JSONB NOT NULL DEFAULT '[]', explanation TEXT, points SMALLINT NOT NULL DEFAULT 1 CHECK (points > 0), UNIQUE(passage_id, question_number));
CREATE TABLE reading_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, test_id UUID NOT NULL REFERENCES reading_tests(id), status practice_status NOT NULL DEFAULT 'in_progress', started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), submitted_at TIMESTAMPTZ, raw_score SMALLINT, total_points SMALLINT);
CREATE TABLE reading_answers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), attempt_id UUID NOT NULL REFERENCES reading_attempts(id) ON DELETE CASCADE, question_id UUID NOT NULL REFERENCES reading_questions(id), answer JSONB, is_correct BOOLEAN, UNIQUE(attempt_id, question_id));

CREATE TABLE writing_tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(250) NOT NULL, task_type writing_task_type NOT NULL, category VARCHAR(50) NOT NULL, prompt TEXT NOT NULL, visual_url TEXT, time_limit_minutes SMALLINT NOT NULL DEFAULT 40, is_published BOOLEAN NOT NULL DEFAULT FALSE, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE writing_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, task_id UUID NOT NULL REFERENCES writing_tasks(id), response_text TEXT NOT NULL, word_count SMALLINT NOT NULL, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE TABLE speaking_tests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title VARCHAR(200) NOT NULL, instructions TEXT, is_published BOOLEAN NOT NULL DEFAULT FALSE, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE speaking_questions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), test_id UUID NOT NULL REFERENCES speaking_tests(id) ON DELETE CASCADE, part speaking_part NOT NULL, question_number SMALLINT NOT NULL, prompt TEXT NOT NULL, cue_points JSONB NOT NULL DEFAULT '[]', preparation_seconds SMALLINT NOT NULL DEFAULT 0, response_seconds SMALLINT NOT NULL DEFAULT 60, UNIQUE(test_id, part, question_number));
CREATE TABLE speaking_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, test_id UUID NOT NULL REFERENCES speaking_tests(id), question_id UUID REFERENCES speaking_questions(id), audio_url TEXT, transcript TEXT, duration_seconds SMALLINT, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE INDEX listening_attempt_user_idx ON listening_attempts(user_id, started_at DESC);
CREATE INDEX reading_attempt_user_idx ON reading_attempts(user_id, started_at DESC);
CREATE INDEX writing_attempt_user_idx ON writing_attempts(user_id, submitted_at DESC);
CREATE INDEX speaking_attempt_user_idx ON speaking_attempts(user_id, submitted_at DESC);
